# world_cup_players_data.py
# Plantillas de las 48 selecciones — Mundial 2026
# Formato: {"name": str, "position": "POR"|"DEF"|"MED"|"DEL", "number": int}

WC_SQUADS = {
    # ─── GRUPO A ───────────────────────────────────────────────────────────────
    "México": [
        {"name": "Guillermo Ochoa",     "position": "POR", "number": 1},
        {"name": "Luis Ángel Malagón",  "position": "POR", "number": 13},
        {"name": "Rodolfo Cota",        "position": "POR", "number": 23},
        {"name": "César Montes",        "position": "DEF", "number": 3},
        {"name": "Jesús Gallardo",      "position": "DEF", "number": 23},
        {"name": "Johan Vásquez",       "position": "DEF", "number": 5},
        {"name": "Gerardo Arteaga",     "position": "DEF", "number": 12},
        {"name": "Jorge Sánchez",       "position": "DEF", "number": 22},
        {"name": "Edson Álvarez",       "position": "MED", "number": 6},
        {"name": "Luis Romo",           "position": "MED", "number": 8},
        {"name": "Roberto Alvarado",    "position": "MED", "number": 19},
        {"name": "Uriel Antuna",        "position": "MED", "number": 21},
        {"name": "Orbelín Pineda",      "position": "MED", "number": 10},
        {"name": "Hirving Lozano",      "position": "DEL", "number": 22},
        {"name": "Henry Martín",        "position": "DEL", "number": 9},
        {"name": "Santiago Giménez",    "position": "DEL", "number": 11},
        {"name": "Alexis Vega",         "position": "DEL", "number": 18},
    ],
    "Sudáfrica": [
        {"name": "Ronwen Williams",     "position": "POR", "number": 1},
        {"name": "Bruce Bvuma",         "position": "POR", "number": 23},
        {"name": "Sifiso Mlungwana",    "position": "POR", "number": 16},
        {"name": "Siyanda Xulu",        "position": "DEF", "number": 5},
        {"name": "Reeve Frosler",       "position": "DEF", "number": 2},
        {"name": "Teboho Mokoena",      "position": "DEF", "number": 4},
        {"name": "Bongani Zungu",       "position": "DEF", "number": 6},
        {"name": "Lyle Foster",         "position": "DEF", "number": 3},
        {"name": "Themba Zwane",        "position": "MED", "number": 10},
        {"name": "Ethan Nkosi",         "position": "MED", "number": 17},
        {"name": "Yusuf Maart",         "position": "MED", "number": 8},
        {"name": "Mothobi Mvala",       "position": "MED", "number": 14},
        {"name": "Percy Tau",           "position": "DEL", "number": 7},
        {"name": "Evidence Makgopa",    "position": "DEL", "number": 9},
        {"name": "Lebo Mothiba",        "position": "DEL", "number": 11},
    ],
    "Corea del Sur": [
        {"name": "Kim Seung-gyu",       "position": "POR", "number": 1},
        {"name": "Jo Hyeon-woo",        "position": "POR", "number": 21},
        {"name": "Song Bum-keun",       "position": "POR", "number": 23},
        {"name": "Kim Min-jae",         "position": "DEF", "number": 3},
        {"name": "Kim Young-gwon",      "position": "DEF", "number": 5},
        {"name": "Kim Jin-su",          "position": "DEF", "number": 12},
        {"name": "Lee Yong",            "position": "DEF", "number": 2},
        {"name": "Jung Woo-young",      "position": "MED", "number": 16},
        {"name": "Hwang In-beom",       "position": "MED", "number": 8},
        {"name": "Son Heung-min",       "position": "MED", "number": 7},
        {"name": "Lee Kang-in",         "position": "MED", "number": 14},
        {"name": "Kwon Chang-hoon",     "position": "MED", "number": 17},
        {"name": "Hwang Hee-chan",      "position": "DEL", "number": 9},
        {"name": "Cho Gue-sung",        "position": "DEL", "number": 11},
        {"name": "Oh Hyeon-gyu",        "position": "DEL", "number": 18},
    ],
    "Rep. Checa": [
        {"name": "Jiří Staněk",         "position": "POR", "number": 1},
        {"name": "Tomáš Vaclík",        "position": "POR", "number": 23},
        {"name": "Aleš Mandous",        "position": "POR", "number": 16},
        {"name": "Tomáš Holeš",         "position": "DEF", "number": 4},
        {"name": "Vladimír Coufal",     "position": "DEF", "number": 2},
        {"name": "David Zima",          "position": "DEF", "number": 5},
        {"name": "Jakub Brabec",        "position": "DEF", "number": 6},
        {"name": "Tomáš Souček",        "position": "MED", "number": 8},
        {"name": "Lukáš Provod",        "position": "MED", "number": 10},
        {"name": "Ondřej Lingr",        "position": "MED", "number": 17},
        {"name": "Jakub Pešek",         "position": "MED", "number": 14},
        {"name": "Patrik Schick",       "position": "DEL", "number": 9},
        {"name": "Adam Hložek",         "position": "DEL", "number": 11},
        {"name": "Jan Kuchta",          "position": "DEL", "number": 18},
        {"name": "Mojmír Chytil",       "position": "DEL", "number": 19},
    ],

    # ─── GRUPO B ───────────────────────────────────────────────────────────────
    "Canadá": [
        {"name": "Milan Borjan",        "position": "POR", "number": 18},
        {"name": "Dayne St. Clair",     "position": "POR", "number": 1},
        {"name": "James Pantemis",      "position": "POR", "number": 23},
        {"name": "Alistair Johnston",   "position": "DEF", "number": 2},
        {"name": "Kamal Miller",        "position": "DEF", "number": 5},
        {"name": "Steven Vitória",      "position": "DEF", "number": 6},
        {"name": "Derek Cornelius",     "position": "DEF", "number": 4},
        {"name": "Tajon Buchanan",      "position": "MED", "number": 11},
        {"name": "Stephen Eustáquio",   "position": "MED", "number": 7},
        {"name": "Ismaël Koné",         "position": "MED", "number": 8},
        {"name": "Richie Laryea",       "position": "MED", "number": 22},
        {"name": "Alphonso Davies",     "position": "DEL", "number": 19},
        {"name": "Jonathan David",      "position": "DEL", "number": 9},
        {"name": "Cyle Larin",          "position": "DEL", "number": 17},
        {"name": "Junior Hoilett",      "position": "DEL", "number": 10},
    ],
    "Bosnia": [
        {"name": "Ibrahim Šehić",       "position": "POR", "number": 1},
        {"name": "Kenan Piric",         "position": "POR", "number": 23},
        {"name": "Nikola Vasilj",       "position": "POR", "number": 12},
        {"name": "Anel Ahmedhodžić",    "position": "DEF", "number": 4},
        {"name": "Nermin Zolotić",      "position": "DEF", "number": 3},
        {"name": "Jusuf Gazibegović",   "position": "DEF", "number": 2},
        {"name": "Ermin Bičakčić",      "position": "DEF", "number": 6},
        {"name": "Miralem Pjanić",      "position": "MED", "number": 8},
        {"name": "Asmir Suljić",        "position": "MED", "number": 10},
        {"name": "Sead Kolašinac",      "position": "MED", "number": 5},
        {"name": "Dario Šimić",         "position": "MED", "number": 14},
        {"name": "Edin Džeko",          "position": "DEL", "number": 9},
        {"name": "Ermedin Demirović",   "position": "DEL", "number": 11},
        {"name": "Amer Gojak",          "position": "DEL", "number": 18},
        {"name": "Dženis Berbić",       "position": "DEL", "number": 7},
    ],
    "Qatar": [
        {"name": "Meshaal Barsham",     "position": "POR", "number": 1},
        {"name": "Yousuf Hassan",       "position": "POR", "number": 23},
        {"name": "Bassel Ghandour",     "position": "POR", "number": 12},
        {"name": "Pedro Miguel",        "position": "DEF", "number": 2},
        {"name": "Abdelkarim Hassan",   "position": "DEF", "number": 3},
        {"name": "Boualem Khoukhi",     "position": "DEF", "number": 5},
        {"name": "Bassam Al-Rawi",      "position": "DEF", "number": 6},
        {"name": "Akram Afif",          "position": "MED", "number": 11},
        {"name": "Karim Boudiaf",       "position": "MED", "number": 8},
        {"name": "Ismaeel Mohammad",    "position": "MED", "number": 7},
        {"name": "Hassan Al-Haydos",    "position": "MED", "number": 10},
        {"name": "Almoez Ali",          "position": "DEL", "number": 19},
        {"name": "Mohammed Muntari",    "position": "DEL", "number": 9},
        {"name": "Ahmed Alaaeldin",     "position": "DEL", "number": 18},
        {"name": "Tameem Al-Mohammadi", "position": "DEL", "number": 17},
    ],
    "Suiza": [
        {"name": "Yann Sommer",         "position": "POR", "number": 1},
        {"name": "Jonas Omlin",         "position": "POR", "number": 12},
        {"name": "Philipp Köhn",        "position": "POR", "number": 23},
        {"name": "Manuel Akanji",       "position": "DEF", "number": 5},
        {"name": "Fabian Schär",        "position": "DEF", "number": 4},
        {"name": "Ricardo Rodríguez",   "position": "DEF", "number": 13},
        {"name": "Silvan Widmer",       "position": "DEF", "number": 2},
        {"name": "Granit Xhaka",        "position": "MED", "number": 10},
        {"name": "Remo Freuler",        "position": "MED", "number": 8},
        {"name": "Xherdan Shaqiri",     "position": "MED", "number": 23},
        {"name": "Michel Aebischer",    "position": "MED", "number": 6},
        {"name": "Breel Embolo",        "position": "DEL", "number": 7},
        {"name": "Noah Okafor",         "position": "DEL", "number": 17},
        {"name": "Ruben Vargas",        "position": "DEL", "number": 20},
        {"name": "Zeki Amdouni",        "position": "DEL", "number": 11},
    ],

    # ─── GRUPO C ───────────────────────────────────────────────────────────────
    "Brasil": [
        {"name": "Alisson Becker",      "position": "POR", "number": 1},
        {"name": "Ederson",             "position": "POR", "number": 23},
        {"name": "Weverton",            "position": "POR", "number": 12},
        {"name": "Marquinhos",          "position": "DEF", "number": 4},
        {"name": "Éder Militão",        "position": "DEF", "number": 3},
        {"name": "Alex Sandro",         "position": "DEF", "number": 6},
        {"name": "Danilo",              "position": "DEF", "number": 2},
        {"name": "Casemiro",            "position": "MED", "number": 5},
        {"name": "Lucas Paquetá",       "position": "MED", "number": 10},
        {"name": "Rodrygo",             "position": "MED", "number": 11},
        {"name": "Vinicius Jr.",        "position": "MED", "number": 20},
        {"name": "Raphinha",            "position": "MED", "number": 19},
        {"name": "Neymar Jr.",          "position": "DEL", "number": 10},
        {"name": "Gabriel Jesus",       "position": "DEL", "number": 9},
        {"name": "Endrick",             "position": "DEL", "number": 7},
        {"name": "Pedro",               "position": "DEL", "number": 21},
    ],
    "Marruecos": [
        {"name": "Yassine Bounou",      "position": "POR", "number": 1},
        {"name": "Munir Mohamedi",      "position": "POR", "number": 12},
        {"name": "Ahmed Red Tagnaouti", "position": "POR", "number": 23},
        {"name": "Achraf Hakimi",       "position": "DEF", "number": 2},
        {"name": "Romain Saïss",        "position": "DEF", "number": 5},
        {"name": "Nayef Aguerd",        "position": "DEF", "number": 6},
        {"name": "Noussair Mazraoui",   "position": "DEF", "number": 3},
        {"name": "Sofyan Amrabat",      "position": "MED", "number": 4},
        {"name": "Azzedine Ounahi",     "position": "MED", "number": 8},
        {"name": "Selim Amallah",       "position": "MED", "number": 7},
        {"name": "Hakim Ziyech",        "position": "MED", "number": 22},
        {"name": "Youssef En-Nesyri",   "position": "DEL", "number": 9},
        {"name": "Sofiane Boufal",      "position": "DEL", "number": 11},
        {"name": "Abde Ezzalzouli",     "position": "DEL", "number": 19},
        {"name": "Walid Cheddira",      "position": "DEL", "number": 18},
    ],
    "Haití": [
        {"name": "Johny Placide",       "position": "POR", "number": 1},
        {"name": "Duckens Nazon",       "position": "POR", "number": 23},
        {"name": "Carlens Arcus",       "position": "POR", "number": 12},
        {"name": "Andrew Bazile",       "position": "DEF", "number": 4},
        {"name": "Kevin Lafrance",      "position": "DEF", "number": 5},
        {"name": "Mechack Jérôme",      "position": "DEF", "number": 3},
        {"name": "Béchir Douibi",       "position": "DEF", "number": 2},
        {"name": "James Léandre",       "position": "MED", "number": 8},
        {"name": "Ernst Etienne",       "position": "MED", "number": 10},
        {"name": "Frantzdy Pierrot",    "position": "MED", "number": 7},
        {"name": "Derrick Étienne",     "position": "MED", "number": 17},
        {"name": "Duckens Nazon",       "position": "DEL", "number": 9},
        {"name": "Steeven Saba",        "position": "DEL", "number": 11},
        {"name": "Ronaldo Damus",       "position": "DEL", "number": 18},
        {"name": "Kervens Belfort",     "position": "DEL", "number": 19},
    ],
    "Escocia": [
        {"name": "Craig Gordon",        "position": "POR", "number": 1},
        {"name": "Liam Kelly",          "position": "POR", "number": 12},
        {"name": "Zander Clark",        "position": "POR", "number": 23},
        {"name": "Andrew Robertson",    "position": "DEF", "number": 3},
        {"name": "Kieran Tierney",      "position": "DEF", "number": 5},
        {"name": "Grant Hanley",        "position": "DEF", "number": 6},
        {"name": "Jack Hendry",         "position": "DEF", "number": 4},
        {"name": "Scott McTominay",     "position": "MED", "number": 8},
        {"name": "John McGinn",         "position": "MED", "number": 7},
        {"name": "Ryan Jack",           "position": "MED", "number": 14},
        {"name": "Billy Gilmour",       "position": "MED", "number": 10},
        {"name": "Che Adams",           "position": "DEL", "number": 9},
        {"name": "Lyndon Dykes",        "position": "DEL", "number": 11},
        {"name": "Ryan Christie",       "position": "DEL", "number": 17},
        {"name": "Stuart Armstrong",    "position": "DEL", "number": 18},
    ],

    # ─── GRUPO D ───────────────────────────────────────────────────────────────
    "USA": [
        {"name": "Matt Turner",         "position": "POR", "number": 1},
        {"name": "Ethan Horvath",       "position": "POR", "number": 12},
        {"name": "Sean Johnson",        "position": "POR", "number": 23},
        {"name": "Sergino Dest",        "position": "DEF", "number": 2},
        {"name": "Tim Ream",            "position": "DEF", "number": 5},
        {"name": "Walker Zimmerman",    "position": "DEF", "number": 3},
        {"name": "DeAndre Yedlin",      "position": "DEF", "number": 21},
        {"name": "Tyler Adams",         "position": "MED", "number": 4},
        {"name": "Weston McKennie",     "position": "MED", "number": 8},
        {"name": "Yunus Musah",         "position": "MED", "number": 6},
        {"name": "Gio Reyna",           "position": "MED", "number": 7},
        {"name": "Christian Pulisic",   "position": "DEL", "number": 10},
        {"name": "Ricardo Pepi",        "position": "DEL", "number": 9},
        {"name": "Josh Sargent",        "position": "DEL", "number": 11},
        {"name": "Folarin Balogun",     "position": "DEL", "number": 17},
    ],
    "Paraguay": [
        {"name": "Antony Silva",        "position": "POR", "number": 1},
        {"name": "Alfredo Aguilar",     "position": "POR", "number": 23},
        {"name": "Rodrigo Muñoz",       "position": "POR", "number": 12},
        {"name": "Gustavo Gómez",       "position": "DEF", "number": 4},
        {"name": "Omar Alderete",       "position": "DEF", "number": 5},
        {"name": "Fabián Balbuena",     "position": "DEF", "number": 3},
        {"name": "Júnior Alonso",       "position": "DEF", "number": 6},
        {"name": "Miguel Almirón",      "position": "MED", "number": 10},
        {"name": "Hernán Pérez",        "position": "MED", "number": 17},
        {"name": "Mathías Villasanti",  "position": "MED", "number": 8},
        {"name": "Ángel Cardozo",       "position": "MED", "number": 14},
        {"name": "Roque Santa Cruz",    "position": "DEL", "number": 9},
        {"name": "Antonio Sanabria",    "position": "DEL", "number": 11},
        {"name": "Blas Riveros",        "position": "DEL", "number": 7},
        {"name": "Alejandro Romero",    "position": "DEL", "number": 19},
    ],
    "Australia": [
        {"name": "Mat Ryan",            "position": "POR", "number": 1},
        {"name": "Danny Vukovic",       "position": "POR", "number": 12},
        {"name": "Andrew Redmayne",     "position": "POR", "number": 23},
        {"name": "Harry Souttar",       "position": "DEF", "number": 5},
        {"name": "Miloš Degenek",       "position": "DEF", "number": 2},
        {"name": "Joel King",           "position": "DEF", "number": 3},
        {"name": "Nathaniel Atkinson",  "position": "DEF", "number": 16},
        {"name": "Aaron Mooy",          "position": "MED", "number": 13},
        {"name": "Ajdin Hrustic",       "position": "MED", "number": 8},
        {"name": "Riley McGree",        "position": "MED", "number": 7},
        {"name": "Keanu Baccus",        "position": "MED", "number": 14},
        {"name": "Mathew Leckie",       "position": "DEL", "number": 11},
        {"name": "Mitchell Duke",       "position": "DEL", "number": 9},
        {"name": "Jason Cummings",      "position": "DEL", "number": 17},
        {"name": "Martin Boyle",        "position": "DEL", "number": 21},
    ],
    "Turquía": [
        {"name": "Altay Bayındır",      "position": "POR", "number": 1},
        {"name": "Uğurcan Çakır",       "position": "POR", "number": 23},
        {"name": "Mert Günok",          "position": "POR", "number": 12},
        {"name": "Merih Demiral",       "position": "DEF", "number": 3},
        {"name": "Zeki Çelik",          "position": "DEF", "number": 2},
        {"name": "Ozan Kabak",          "position": "DEF", "number": 5},
        {"name": "Ferdi Kadıoğlu",      "position": "DEF", "number": 4},
        {"name": "Hakan Çalhanoğlu",    "position": "MED", "number": 10},
        {"name": "Okay Yokuşlu",        "position": "MED", "number": 8},
        {"name": "Kerem Aktürkoğlu",    "position": "MED", "number": 11},
        {"name": "Orkun Kökçü",         "position": "MED", "number": 6},
        {"name": "Arda Güler",          "position": "DEL", "number": 17},
        {"name": "Cenk Tosun",          "position": "DEL", "number": 9},
        {"name": "Baris Alper Yilmaz",  "position": "DEL", "number": 7},
        {"name": "Halil Dervişoğlu",    "position": "DEL", "number": 19},
    ],

    # ─── GRUPO E ───────────────────────────────────────────────────────────────
    "Alemania": [
        {"name": "Manuel Neuer",        "position": "POR", "number": 1},
        {"name": "Marc-André ter Stegen","position": "POR", "number": 22},
        {"name": "Oliver Baumann",      "position": "POR", "number": 12},
        {"name": "Antonio Rüdiger",     "position": "DEF", "number": 2},
        {"name": "Joshua Kimmich",      "position": "DEF", "number": 6},
        {"name": "Nico Schlotterbeck",  "position": "DEF", "number": 4},
        {"name": "David Raum",          "position": "DEF", "number": 3},
        {"name": "Toni Kroos",          "position": "MED", "number": 8},
        {"name": "Ilkay Gündoğan",      "position": "MED", "number": 21},
        {"name": "Leon Goretzka",       "position": "MED", "number": 14},
        {"name": "Florian Wirtz",       "position": "MED", "number": 10},
        {"name": "Jamal Musiala",       "position": "DEL", "number": 7},
        {"name": "Kai Havertz",         "position": "DEL", "number": 9},
        {"name": "Serge Gnabry",        "position": "DEL", "number": 20},
        {"name": "Niclas Füllkrug",     "position": "DEL", "number": 11},
    ],
    "Curaçao": [
        {"name": "Eloy Room",           "position": "POR", "number": 1},
        {"name": "Gianni Zuiverloon",   "position": "POR", "number": 23},
        {"name": "Cuco Martina",        "position": "POR", "number": 12},
        {"name": "Riechedly Bazoer",    "position": "DEF", "number": 5},
        {"name": "Rangelo Janga",       "position": "DEF", "number": 3},
        {"name": "Gaston Celina",       "position": "DEF", "number": 4},
        {"name": "Elson Hooi",          "position": "DEF", "number": 2},
        {"name": "Leandro Bacuna",      "position": "MED", "number": 8},
        {"name": "Jurickson Profar",    "position": "MED", "number": 10},
        {"name": "Brandley Kuwas",      "position": "MED", "number": 7},
        {"name": "Quentin Krekels",     "position": "MED", "number": 14},
        {"name": "Kenji Gorré",         "position": "DEL", "number": 9},
        {"name": "Charlison Benschop",  "position": "DEL", "number": 11},
        {"name": "Gino van Kessel",     "position": "DEL", "number": 17},
        {"name": "Ryan Leef",           "position": "DEL", "number": 19},
    ],
    "Costa de Marfil": [
        {"name": "Badra Ali Sangaré",   "position": "POR", "number": 1},
        {"name": "Sylvain Gbohouo",     "position": "POR", "number": 23},
        {"name": "Ali Badra Sangaré",   "position": "POR", "number": 12},
        {"name": "Serge Aurier",        "position": "DEF", "number": 2},
        {"name": "Eric Bailly",         "position": "DEF", "number": 5},
        {"name": "Wilfried Singo",      "position": "DEF", "number": 3},
        {"name": "Simon Deli",          "position": "DEF", "number": 6},
        {"name": "Franck Kessié",       "position": "MED", "number": 4},
        {"name": "Seko Fofana",         "position": "MED", "number": 8},
        {"name": "Jean-Philippe Gbamin","position": "MED", "number": 14},
        {"name": "Ibrahim Sangaré",     "position": "MED", "number": 10},
        {"name": "Nicolas Pépé",        "position": "DEL", "number": 7},
        {"name": "Wilfried Zaha",       "position": "DEL", "number": 17},
        {"name": "Sébastien Haller",    "position": "DEL", "number": 9},
        {"name": "Jonathan Kodjia",     "position": "DEL", "number": 11},
    ],
    "Ecuador": [
        {"name": "Hernán Galíndez",     "position": "POR", "number": 1},
        {"name": "Alexander Domínguez", "position": "POR", "number": 12},
        {"name": "Moisés Ramírez",      "position": "POR", "number": 23},
        {"name": "Piero Hincapié",      "position": "DEF", "number": 3},
        {"name": "Félix Torres",        "position": "DEF", "number": 6},
        {"name": "Angelo Preciado",     "position": "DEF", "number": 2},
        {"name": "Robert Arboleda",     "position": "DEF", "number": 5},
        {"name": "Carlos Gruezo",       "position": "MED", "number": 16},
        {"name": "Moisés Caicedo",      "position": "MED", "number": 8},
        {"name": "Gonzalo Plata",       "position": "MED", "number": 11},
        {"name": "Jeremy Sarmiento",    "position": "MED", "number": 17},
        {"name": "Ángel Mena",          "position": "DEL", "number": 7},
        {"name": "Énner Valencia",      "position": "DEL", "number": 9},
        {"name": "Michael Estrada",     "position": "DEL", "number": 19},
        {"name": "Djorkaeff Reasco",    "position": "DEL", "number": 21},
    ],

    # ─── GRUPO F ───────────────────────────────────────────────────────────────
    "Países Bajos": [
        {"name": "Andries Noppert",     "position": "POR", "number": 1},
        {"name": "Remko Pasveer",       "position": "POR", "number": 23},
        {"name": "Jasper Cillessen",    "position": "POR", "number": 12},
        {"name": "Virgil van Dijk",     "position": "DEF", "number": 4},
        {"name": "Matthijs de Ligt",    "position": "DEF", "number": 3},
        {"name": "Daley Blind",         "position": "DEF", "number": 5},
        {"name": "Denzel Dumfries",     "position": "DEF", "number": 22},
        {"name": "Frenkie de Jong",     "position": "MED", "number": 21},
        {"name": "Georginio Wijnaldum", "position": "MED", "number": 8},
        {"name": "Xavi Simons",         "position": "MED", "number": 10},
        {"name": "Teun Koopmeiners",    "position": "MED", "number": 14},
        {"name": "Memphis Depay",       "position": "DEL", "number": 10},
        {"name": "Cody Gakpo",          "position": "DEL", "number": 11},
        {"name": "Donyell Malen",       "position": "DEL", "number": 7},
        {"name": "Wout Weghorst",       "position": "DEL", "number": 9},
    ],
    "Japón": [
        {"name": "Shuichi Gonda",       "position": "POR", "number": 1},
        {"name": "Zion Suzuki",         "position": "POR", "number": 23},
        {"name": "Kosei Tani",          "position": "POR", "number": 12},
        {"name": "Maya Yoshida",        "position": "DEF", "number": 3},
        {"name": "Ko Itakura",          "position": "DEF", "number": 4},
        {"name": "Hiroki Sakai",        "position": "DEF", "number": 2},
        {"name": "Yuto Nagatomo",       "position": "DEF", "number": 5},
        {"name": "Wataru Endo",         "position": "MED", "number": 6},
        {"name": "Gaku Shibasaki",      "position": "MED", "number": 8},
        {"name": "Junya Ito",           "position": "MED", "number": 7},
        {"name": "Takumi Minamino",     "position": "MED", "number": 10},
        {"name": "Ritsu Doan",          "position": "DEL", "number": 11},
        {"name": "Daichi Kamada",       "position": "DEL", "number": 9},
        {"name": "Ayase Ueda",          "position": "DEL", "number": 18},
        {"name": "Kaoru Mitoma",        "position": "DEL", "number": 17},
    ],
    "Suecia": [
        {"name": "Robin Olsen",         "position": "POR", "number": 1},
        {"name": "Karl-Johan Johnsson", "position": "POR", "number": 12},
        {"name": "Andreas Linde",       "position": "POR", "number": 23},
        {"name": "Victor Lindelöf",     "position": "DEF", "number": 2},
        {"name": "Alexander Isak",      "position": "DEF", "number": 14},
        {"name": "Marcus Danielson",    "position": "DEF", "number": 5},
        {"name": "Emil Krafth",         "position": "DEF", "number": 3},
        {"name": "Albin Ekdal",         "position": "MED", "number": 8},
        {"name": "Emil Forsberg",       "position": "MED", "number": 10},
        {"name": "Dejan Kulusevski",    "position": "MED", "number": 7},
        {"name": "Jesper Karlsson",     "position": "MED", "number": 17},
        {"name": "Zlatan Ibrahimović",  "position": "DEL", "number": 9},
        {"name": "Anthony Elanga",      "position": "DEL", "number": 11},
        {"name": "Viktor Gyökeres",     "position": "DEL", "number": 19},
        {"name": "Robin Quaison",       "position": "DEL", "number": 20},
    ],
    "Túnez": [
        {"name": "Aymen Dahmen",        "position": "POR", "number": 1},
        {"name": "Bechir Ben Said",     "position": "POR", "number": 12},
        {"name": "Moez Ben Cherifia",   "position": "POR", "number": 23},
        {"name": "Montassar Talbi",     "position": "DEF", "number": 4},
        {"name": "Dylan Bronn",         "position": "DEF", "number": 6},
        {"name": "Wajdi Kechrida",      "position": "DEF", "number": 2},
        {"name": "Ali Maaloul",         "position": "DEF", "number": 3},
        {"name": "Ellyes Skhiri",       "position": "MED", "number": 8},
        {"name": "Aïssa Laïdouni",      "position": "MED", "number": 10},
        {"name": "Naim Sliti",          "position": "MED", "number": 7},
        {"name": "Ghailene Chaalali",   "position": "MED", "number": 14},
        {"name": "Wahbi Khazri",        "position": "DEL", "number": 11},
        {"name": "Youssef Msakni",      "position": "DEL", "number": 17},
        {"name": "Issam Jebali",        "position": "DEL", "number": 9},
        {"name": "Saifeddine Khaoui",   "position": "DEL", "number": 19},
    ],

    # ─── GRUPO G ───────────────────────────────────────────────────────────────
    "Bélgica": [
        {"name": "Thibaut Courtois",    "position": "POR", "number": 1},
        {"name": "Koen Casteels",       "position": "POR", "number": 12},
        {"name": "Matz Sels",           "position": "POR", "number": 23},
        {"name": "Toby Alderweireld",   "position": "DEF", "number": 2},
        {"name": "Jan Vertonghen",      "position": "DEF", "number": 5},
        {"name": "Thomas Meunier",      "position": "DEF", "number": 3},
        {"name": "Arthur Theate",       "position": "DEF", "number": 4},
        {"name": "Kevin De Bruyne",     "position": "MED", "number": 7},
        {"name": "Axel Witsel",         "position": "MED", "number": 6},
        {"name": "Youri Tielemans",     "position": "MED", "number": 8},
        {"name": "Leandro Trossard",    "position": "MED", "number": 11},
        {"name": "Romelu Lukaku",       "position": "DEL", "number": 9},
        {"name": "Eden Hazard",         "position": "DEL", "number": 10},
        {"name": "Dries Mertens",       "position": "DEL", "number": 14},
        {"name": "Lois Openda",         "position": "DEL", "number": 19},
    ],
    "Egipto": [
        {"name": "Mohamed El-Shenawy",  "position": "POR", "number": 1},
        {"name": "Mohamed Abou Gabal",  "position": "POR", "number": 23},
        {"name": "Ahmed El Shenawi",    "position": "POR", "number": 12},
        {"name": "Ahmed Hegazi",        "position": "DEF", "number": 5},
        {"name": "Omar Kamal",          "position": "DEF", "number": 4},
        {"name": "Akram Tawfik",        "position": "DEF", "number": 2},
        {"name": "Mohamed Abdel-Moneim","position": "DEF", "number": 3},
        {"name": "Tarek Hamed",         "position": "MED", "number": 8},
        {"name": "Mohamed Elneny",      "position": "MED", "number": 6},
        {"name": "Amr El-Sulaya",       "position": "MED", "number": 14},
        {"name": "Mahmoud 'Trezeguet'", "position": "MED", "number": 10},
        {"name": "Mohamed Salah",       "position": "DEL", "number": 11},
        {"name": "Mostafa Mohamed",     "position": "DEL", "number": 9},
        {"name": "Omar Marmoush",       "position": "DEL", "number": 7},
        {"name": "Ramadan Sobhi",       "position": "DEL", "number": 17},
    ],
    "Irán": [
        {"name": "Alireza Beiranvand",  "position": "POR", "number": 1},
        {"name": "Hossein Hosseini",    "position": "POR", "number": 12},
        {"name": "Payam Niazmand",      "position": "POR", "number": 23},
        {"name": "Milad Mohammadi",     "position": "DEF", "number": 3},
        {"name": "Rouzbeh Cheshmi",     "position": "DEF", "number": 5},
        {"name": "Majid Hosseini",      "position": "DEF", "number": 6},
        {"name": "Sadegh Moharrami",    "position": "DEF", "number": 2},
        {"name": "Saeid Ezatolahi",     "position": "MED", "number": 8},
        {"name": "Ali Gholizadeh",      "position": "MED", "number": 7},
        {"name": "Ahmad Noorollahi",    "position": "MED", "number": 14},
        {"name": "Mehdi Torabi",        "position": "MED", "number": 10},
        {"name": "Mehdi Taremi",        "position": "DEL", "number": 9},
        {"name": "Sardar Azmoun",       "position": "DEL", "number": 20},
        {"name": "Karim Ansarifard",    "position": "DEL", "number": 17},
        {"name": "Allahyar Sayyadmanesh","position": "DEL", "number": 19},
    ],
    "Nueva Zelanda": [
        {"name": "Stefan Marinovic",    "position": "POR", "number": 1},
        {"name": "Michael Woud",        "position": "POR", "number": 12},
        {"name": "Oliver Sail",         "position": "POR", "number": 23},
        {"name": "Winston Reid",        "position": "DEF", "number": 5},
        {"name": "Niko Kirwan",         "position": "DEF", "number": 4},
        {"name": "Liberato Cacace",     "position": "DEF", "number": 3},
        {"name": "Elijah Just",         "position": "DEF", "number": 2},
        {"name": "Clayton Lewis",       "position": "MED", "number": 8},
        {"name": "Joe Bell",            "position": "MED", "number": 6},
        {"name": "Alex Rufer",          "position": "MED", "number": 10},
        {"name": "Callum McCowatt",     "position": "MED", "number": 14},
        {"name": "Chris Wood",          "position": "DEL", "number": 9},
        {"name": "Caleb Watts",         "position": "DEL", "number": 11},
        {"name": "Matthew Garbett",     "position": "DEL", "number": 17},
        {"name": "Hamish Watson",       "position": "DEL", "number": 18},
    ],

    # ─── GRUPO H ───────────────────────────────────────────────────────────────
    "España": [
        {"name": "Unai Simón",          "position": "POR", "number": 23},
        {"name": "David Raya",          "position": "POR", "number": 1},
        {"name": "Robert Sánchez",      "position": "POR", "number": 13},
        {"name": "Dani Carvajal",       "position": "DEF", "number": 2},
        {"name": "Aymeric Laporte",     "position": "DEF", "number": 14},
        {"name": "Pau Cubarsí",         "position": "DEF", "number": 24},
        {"name": "Alejandro Balde",     "position": "DEF", "number": 3},
        {"name": "Rodri",               "position": "MED", "number": 16},
        {"name": "Pedri",               "position": "MED", "number": 26},
        {"name": "Gavi",                "position": "MED", "number": 9},
        {"name": "Fabián Ruiz",         "position": "MED", "number": 8},
        {"name": "Lamine Yamal",        "position": "DEL", "number": 19},
        {"name": "Nico Williams",       "position": "DEL", "number": 17},
        {"name": "Álvaro Morata",       "position": "DEL", "number": 7},
        {"name": "Dani Olmo",           "position": "DEL", "number": 10},
    ],
    "Cabo Verde": [
        {"name": "Vozinha",             "position": "POR", "number": 1},
        {"name": "Luís Semedo",         "position": "POR", "number": 23},
        {"name": "Edi Semedo",          "position": "POR", "number": 12},
        {"name": "Dylan Tavares",       "position": "DEF", "number": 2},
        {"name": "Stopira",             "position": "DEF", "number": 6},
        {"name": "Félix Borges",        "position": "DEF", "number": 4},
        {"name": "Zé Luís",             "position": "DEF", "number": 3},
        {"name": "Kenny Rocha",         "position": "MED", "number": 8},
        {"name": "Jamiro Monteiro",     "position": "MED", "number": 10},
        {"name": "Garry Rodrigues",     "position": "MED", "number": 11},
        {"name": "Marco Soares",        "position": "MED", "number": 14},
        {"name": "Ryan Mendes",         "position": "DEL", "number": 7},
        {"name": "Djaniny",             "position": "DEL", "number": 9},
        {"name": "Jovane Cabral",       "position": "DEL", "number": 17},
        {"name": "Sandro",              "position": "DEL", "number": 19},
    ],
    "Arabia Saudita": [
        {"name": "Mohammed Al-Owais",   "position": "POR", "number": 1},
        {"name": "Fawaz Al-Qarni",      "position": "POR", "number": 12},
        {"name": "Nawaf Al-Aqidi",      "position": "POR", "number": 23},
        {"name": "Ali Al-Bulaihi",      "position": "DEF", "number": 13},
        {"name": "Sultan Al-Ghannam",   "position": "DEF", "number": 5},
        {"name": "Mohammed Al-Burayk",  "position": "DEF", "number": 3},
        {"name": "Saud Abdulhamid",     "position": "DEF", "number": 2},
        {"name": "Salman Al-Faraj",     "position": "MED", "number": 4},
        {"name": "Hattan Bahebri",      "position": "MED", "number": 11},
        {"name": "Mohamed Kanno",       "position": "MED", "number": 6},
        {"name": "Sami Al-Najei",       "position": "MED", "number": 8},
        {"name": "Salem Al-Dawsari",    "position": "DEL", "number": 10},
        {"name": "Firas Al-Buraikan",   "position": "DEL", "number": 9},
        {"name": "Marwan Al-Sahafi",    "position": "DEL", "number": 18},
        {"name": "Haitham Asiri",       "position": "DEL", "number": 14},
    ],
    "Uruguay": [
        {"name": "Fernando Muslera",    "position": "POR", "number": 1},
        {"name": "Sergio Rochet",       "position": "POR", "number": 23},
        {"name": "Sebastián Sosa",      "position": "POR", "number": 12},
        {"name": "José María Giménez",  "position": "DEF", "number": 2},
        {"name": "Diego Godín",         "position": "DEF", "number": 3},
        {"name": "Ronald Araújo",       "position": "DEF", "number": 4},
        {"name": "Guillermo Varela",    "position": "DEF", "number": 16},
        {"name": "Federico Valverde",   "position": "MED", "number": 8},
        {"name": "Matías Vecino",       "position": "MED", "number": 7},
        {"name": "Rodrigo Bentancur",   "position": "MED", "number": 5},
        {"name": "Manuel Ugarte",       "position": "MED", "number": 15},
        {"name": "Luis Suárez",         "position": "DEL", "number": 9},
        {"name": "Darwin Núñez",        "position": "DEL", "number": 11},
        {"name": "Edinson Cavani",      "position": "DEL", "number": 21},
        {"name": "Nicolás De La Cruz",  "position": "DEL", "number": 10},
    ],

    # ─── GRUPO I ───────────────────────────────────────────────────────────────
    "Francia": [
        {"name": "Mike Maignan",        "position": "POR", "number": 1},
        {"name": "Alphonse Areola",     "position": "POR", "number": 23},
        {"name": "Brice Samba",         "position": "POR", "number": 16},
        {"name": "Jules Koundé",        "position": "DEF", "number": 5},
        {"name": "Raphaël Varane",      "position": "DEF", "number": 4},
        {"name": "Theo Hernández",      "position": "DEF", "number": 22},
        {"name": "Dayot Upamecano",     "position": "DEF", "number": 15},
        {"name": "Aurélien Tchouaméni", "position": "MED", "number": 8},
        {"name": "Eduardo Camavinga",   "position": "MED", "number": 14},
        {"name": "Adrien Rabiot",       "position": "MED", "number": 25},
        {"name": "Antoine Griezmann",   "position": "MED", "number": 7},
        {"name": "Kylian Mbappé",       "position": "DEL", "number": 10},
        {"name": "Ousmane Dembélé",     "position": "DEL", "number": 11},
        {"name": "Marcus Thuram",       "position": "DEL", "number": 9},
        {"name": "Randal Kolo Muani",   "position": "DEL", "number": 19},
    ],
    "Senegal": [
        {"name": "Édouard Mendy",       "position": "POR", "number": 1},
        {"name": "Alfred Gomis",        "position": "POR", "number": 23},
        {"name": "Seny Dieng",          "position": "POR", "number": 12},
        {"name": "Kalidou Koulibaly",   "position": "DEF", "number": 3},
        {"name": "Abdou Diallo",        "position": "DEF", "number": 5},
        {"name": "Youssouf Sabaly",     "position": "DEF", "number": 2},
        {"name": "Ibrahima Mbaye",      "position": "DEF", "number": 6},
        {"name": "Idrissa Gana Gueye",  "position": "MED", "number": 8},
        {"name": "Cheikhou Kouyaté",    "position": "MED", "number": 6},
        {"name": "Pape Matar Sarr",     "position": "MED", "number": 14},
        {"name": "Nampalys Mendy",      "position": "MED", "number": 10},
        {"name": "Sadio Mané",          "position": "DEL", "number": 10},
        {"name": "Ismaila Sarr",        "position": "DEL", "number": 17},
        {"name": "Boulaye Dia",         "position": "DEL", "number": 9},
        {"name": "Nicolas Jackson",     "position": "DEL", "number": 19},
    ],
    "Irak": [
        {"name": "Jalal Hassan",        "position": "POR", "number": 1},
        {"name": "Mohammed Hameed",     "position": "POR", "number": 23},
        {"name": "Dhurgham Ismail",     "position": "POR", "number": 12},
        {"name": "Ali Adnan",           "position": "DEF", "number": 3},
        {"name": "Salam Shakir",        "position": "DEF", "number": 5},
        {"name": "Rebin Sulaka",        "position": "DEF", "number": 4},
        {"name": "Ahmed Ibrahim",       "position": "DEF", "number": 2},
        {"name": "Alaa Abbas",          "position": "MED", "number": 8},
        {"name": "Amjed Attwan",        "position": "MED", "number": 10},
        {"name": "Bashar Resan",        "position": "MED", "number": 6},
        {"name": "Safaa Hadi",          "position": "MED", "number": 14},
        {"name": "Mohanad Ali",         "position": "DEL", "number": 9},
        {"name": "Amir Al-Ammari",      "position": "DEL", "number": 7},
        {"name": "Hussain Ali",         "position": "DEL", "number": 11},
        {"name": "Karrar Mohammed",     "position": "DEL", "number": 17},
    ],
    "Noruega": [
        {"name": "Ørjan Nyland",        "position": "POR", "number": 1},
        {"name": "Rune Jarstein",       "position": "POR", "number": 23},
        {"name": "Mathias Dyngeland",   "position": "POR", "number": 12},
        {"name": "Leo Skiri Østigård",  "position": "DEF", "number": 5},
        {"name": "Stefan Strandberg",   "position": "DEF", "number": 6},
        {"name": "Birger Meling",       "position": "DEF", "number": 3},
        {"name": "Andreas Hanche-Olsen","position": "DEF", "number": 4},
        {"name": "Martin Ødegaard",     "position": "MED", "number": 8},
        {"name": "Sander Berge",        "position": "MED", "number": 6},
        {"name": "Morten Thorsby",      "position": "MED", "number": 14},
        {"name": "Fredrik Aursnes",     "position": "MED", "number": 10},
        {"name": "Erling Haaland",      "position": "DEL", "number": 9},
        {"name": "Alexander Sørloth",   "position": "DEL", "number": 11},
        {"name": "Ola Solbakken",       "position": "DEL", "number": 17},
        {"name": "Antonio Nusa",        "position": "DEL", "number": 19},
    ],

    # ─── GRUPO J ───────────────────────────────────────────────────────────────
    "Argentina": [
        {"name": "Emiliano Martínez",   "position": "POR", "number": 23},
        {"name": "Franco Armani",       "position": "POR", "number": 1},
        {"name": "Gerónimo Rulli",      "position": "POR", "number": 12},
        {"name": "Cristian Romero",     "position": "DEF", "number": 13},
        {"name": "Nicolás Otamendi",    "position": "DEF", "number": 19},
        {"name": "Nahuel Molina",       "position": "DEF", "number": 26},
        {"name": "Marcos Acuña",        "position": "DEF", "number": 8},
        {"name": "Rodrigo De Paul",     "position": "MED", "number": 7},
        {"name": "Leandro Paredes",     "position": "MED", "number": 5},
        {"name": "Enzo Fernández",      "position": "MED", "number": 24},
        {"name": "Alexis Mac Allister", "position": "MED", "number": 20},
        {"name": "Lionel Messi",        "position": "DEL", "number": 10},
        {"name": "Ángel Di María",      "position": "DEL", "number": 11},
        {"name": "Lautaro Martínez",    "position": "DEL", "number": 22},
        {"name": "Julián Álvarez",      "position": "DEL", "number": 9},
    ],
    "Argelia": [
        {"name": "Raïs Mbolhi",         "position": "POR", "number": 1},
        {"name": "Farouk Chafai",       "position": "POR", "number": 23},
        {"name": "Alexandre Oukidja",   "position": "POR", "number": 12},
        {"name": "Ramy Bensebaini",     "position": "DEF", "number": 3},
        {"name": "Djamel Benlamri",     "position": "DEF", "number": 6},
        {"name": "Hicham Boudaoui",     "position": "DEF", "number": 4},
        {"name": "Aïssa Mandi",         "position": "DEF", "number": 5},
        {"name": "Sofiane Feghouli",    "position": "MED", "number": 7},
        {"name": "Nabil Bentaleb",      "position": "MED", "number": 8},
        {"name": "Youcef Atal",         "position": "MED", "number": 2},
        {"name": "Samir Benrahma",      "position": "MED", "number": 10},
        {"name": "Islam Slimani",       "position": "DEL", "number": 9},
        {"name": "Andy Delort",         "position": "DEL", "number": 11},
        {"name": "Baghdad Bounedjah",   "position": "DEL", "number": 17},
        {"name": "Yacine Brahimi",      "position": "DEL", "number": 14},
    ],
    "Austria": [
        {"name": "Patrick Pentz",       "position": "POR", "number": 1},
        {"name": "Daniel Bachmann",     "position": "POR", "number": 23},
        {"name": "Alexander Schlager",  "position": "POR", "number": 12},
        {"name": "David Alaba",         "position": "DEF", "number": 8},
        {"name": "Stefan Posch",        "position": "DEF", "number": 5},
        {"name": "Phillipp Mwene",      "position": "DEF", "number": 3},
        {"name": "Maximilian Wöber",    "position": "DEF", "number": 4},
        {"name": "Konrad Laimer",       "position": "MED", "number": 10},
        {"name": "Marcel Sabitzer",     "position": "MED", "number": 7},
        {"name": "Florian Grillitsch",  "position": "MED", "number": 6},
        {"name": "Nicolas Seiwald",     "position": "MED", "number": 14},
        {"name": "Marko Arnautović",    "position": "DEL", "number": 9},
        {"name": "Michael Gregoritsch", "position": "DEL", "number": 11},
        {"name": "Christoph Baumgartner","position": "DEL", "number": 17},
        {"name": "Patrick Wimmer",      "position": "DEL", "number": 19},
    ],
    "Jordania": [
        {"name": "Amer Shafi",          "position": "POR", "number": 1},
        {"name": "Moh'd Abu Laila",     "position": "POR", "number": 23},
        {"name": "Yazan Al-Arab",       "position": "POR", "number": 12},
        {"name": "Zaid Al-Dehneh",      "position": "DEF", "number": 5},
        {"name": "Basman Alawadi",      "position": "DEF", "number": 3},
        {"name": "Ahmad Saleh",         "position": "DEF", "number": 4},
        {"name": "Oday Dabbagh",        "position": "DEF", "number": 2},
        {"name": "Mousa Suleiman",      "position": "MED", "number": 8},
        {"name": "Baha' Faisal",        "position": "MED", "number": 10},
        {"name": "Raed Ereiqat",        "position": "MED", "number": 14},
        {"name": "Yazan Al-Naimat",     "position": "MED", "number": 7},
        {"name": "Islam Al-Munaizel",   "position": "DEL", "number": 9},
        {"name": "Amro Al-Amsah",       "position": "DEL", "number": 11},
        {"name": "Ahmad Abu Helo",      "position": "DEL", "number": 17},
        {"name": "Mahmoud Al-Mardi",    "position": "DEL", "number": 19},
    ],

    # ─── GRUPO K ───────────────────────────────────────────────────────────────
    "Portugal": [
        {"name": "Rui Patrício",        "position": "POR", "number": 1},
        {"name": "Diogo Costa",         "position": "POR", "number": 23},
        {"name": "José Sá",             "position": "POR", "number": 12},
        {"name": "Rúben Dias",          "position": "DEF", "number": 4},
        {"name": "Pepe",                "position": "DEF", "number": 3},
        {"name": "João Cancelo",        "position": "DEF", "number": 20},
        {"name": "Nuno Mendes",         "position": "DEF", "number": 19},
        {"name": "Vitinha",             "position": "MED", "number": 8},
        {"name": "João Palhinha",       "position": "MED", "number": 26},
        {"name": "Bruno Fernandes",     "position": "MED", "number": 8},
        {"name": "Bernardo Silva",      "position": "MED", "number": 10},
        {"name": "Cristiano Ronaldo",   "position": "DEL", "number": 7},
        {"name": "Rafael Leão",         "position": "DEL", "number": 17},
        {"name": "Gonçalo Ramos",       "position": "DEL", "number": 9},
        {"name": "João Félix",          "position": "DEL", "number": 11},
    ],
    "DR Congo": [
        {"name": "Nico Bolly",          "position": "POR", "number": 1},
        {"name": "Joël Kiassumbua",     "position": "POR", "number": 23},
        {"name": "Benjamin Moukandjo",  "position": "POR", "number": 12},
        {"name": "Joël Kimwaki",        "position": "DEF", "number": 5},
        {"name": "Arthur Masuaku",      "position": "DEF", "number": 3},
        {"name": "Marcel Tisserand",    "position": "DEF", "number": 6},
        {"name": "Chancel Mbemba",      "position": "DEF", "number": 4},
        {"name": "Yannick Bolasie",     "position": "MED", "number": 11},
        {"name": "Neeskens Kebano",     "position": "MED", "number": 8},
        {"name": "Gedeon Kalulu",       "position": "MED", "number": 10},
        {"name": "Gaël Kakuta",         "position": "MED", "number": 7},
        {"name": "Youssouf Mulumbu",    "position": "MED", "number": 14},
        {"name": "Cédric Bakambu",      "position": "DEL", "number": 9},
        {"name": "Dieudonne Mbokani",   "position": "DEL", "number": 17},
        {"name": "Benik Afobe",         "position": "DEL", "number": 19},
    ],
    "Uzbekistán": [
        {"name": "Utkir Yusupov",       "position": "POR", "number": 1},
        {"name": "Bunyod Pardaev",      "position": "POR", "number": 23},
        {"name": "Otabek Shukurov",     "position": "POR", "number": 12},
        {"name": "Sherzod Nasimov",     "position": "DEF", "number": 3},
        {"name": "Akbar Tursunov",      "position": "DEF", "number": 5},
        {"name": "Eldor Shomurodov",    "position": "DEF", "number": 4},
        {"name": "Akmal Shomurodov",    "position": "DEF", "number": 2},
        {"name": "Odil Ahmedov",        "position": "MED", "number": 6},
        {"name": "Jaloliddin Masharipov","position": "MED", "number": 10},
        {"name": "Azizbek Turgunboev",  "position": "MED", "number": 8},
        {"name": "Otabek Fattoyev",     "position": "MED", "number": 14},
        {"name": "Eldor Shomurodov",    "position": "DEL", "number": 9},
        {"name": "Sardor Rashidov",     "position": "DEL", "number": 11},
        {"name": "Dostonbek Khamdamov", "position": "DEL", "number": 17},
        {"name": "Shamsiddin Karimov",  "position": "DEL", "number": 19},
    ],
    "Colombia": [
        {"name": "David Ospina",        "position": "POR", "number": 1},
        {"name": "Camilo Vargas",       "position": "POR", "number": 12},
        {"name": "Álvaro Montero",      "position": "POR", "number": 23},
        {"name": "Davinson Sánchez",    "position": "DEF", "number": 2},
        {"name": "Yerry Mina",          "position": "DEF", "number": 13},
        {"name": "Johan Mojica",        "position": "DEF", "number": 3},
        {"name": "Daniel Muñoz",        "position": "DEF", "number": 22},
        {"name": "Wilmar Barrios",      "position": "MED", "number": 5},
        {"name": "Mateus Uribe",        "position": "MED", "number": 15},
        {"name": "James Rodríguez",     "position": "MED", "number": 10},
        {"name": "Juan Cuadrado",       "position": "MED", "number": 11},
        {"name": "Luis Díaz",           "position": "DEL", "number": 7},
        {"name": "Radamel Falcao",      "position": "DEL", "number": 9},
        {"name": "Jhon Durán",          "position": "DEL", "number": 17},
        {"name": "Rafael Santos Borré", "position": "DEL", "number": 19},
    ],

    # ─── GRUPO L ───────────────────────────────────────────────────────────────
    "Inglaterra": [
        {"name": "Jordan Pickford",     "position": "POR", "number": 1},
        {"name": "Nick Pope",           "position": "POR", "number": 22},
        {"name": "Dean Henderson",      "position": "POR", "number": 13},
        {"name": "Kieran Trippier",     "position": "DEF", "number": 12},
        {"name": "Harry Maguire",       "position": "DEF", "number": 6},
        {"name": "Luke Shaw",           "position": "DEF", "number": 3},
        {"name": "Trent Alexander-Arnold","position": "DEF", "number": 2},
        {"name": "Declan Rice",         "position": "MED", "number": 4},
        {"name": "Jude Bellingham",     "position": "MED", "number": 22},
        {"name": "Mason Mount",         "position": "MED", "number": 19},
        {"name": "Phil Foden",          "position": "MED", "number": 11},
        {"name": "Harry Kane",          "position": "DEL", "number": 9},
        {"name": "Bukayo Saka",         "position": "DEL", "number": 7},
        {"name": "Marcus Rashford",     "position": "DEL", "number": 10},
        {"name": "Raheem Sterling",     "position": "DEL", "number": 20},
    ],
    "Croacia": [
        {"name": "Dominik Livaković",   "position": "POR", "number": 1},
        {"name": "Ivo Grbić",           "position": "POR", "number": 12},
        {"name": "Ivica Ivušić",        "position": "POR", "number": 23},
        {"name": "Joško Gvardiol",      "position": "DEF", "number": 24},
        {"name": "Dejan Lovren",        "position": "DEF", "number": 6},
        {"name": "Borna Sosa",          "position": "DEF", "number": 3},
        {"name": "Josip Juranović",     "position": "DEF", "number": 2},
        {"name": "Luka Modrić",         "position": "MED", "number": 10},
        {"name": "Marcelo Brozović",    "position": "MED", "number": 11},
        {"name": "Mateo Kovačić",       "position": "MED", "number": 8},
        {"name": "Ivan Perišić",        "position": "MED", "number": 4},
        {"name": "Andrej Kramarić",     "position": "DEL", "number": 9},
        {"name": "Ivan Rakitić",        "position": "DEL", "number": 7},
        {"name": "Bruno Petković",      "position": "DEL", "number": 16},
        {"name": "Marko Livaja",        "position": "DEL", "number": 18},
    ],
    "Ghana": [
        {"name": "Lawrence Ati-Zigi",   "position": "POR", "number": 1},
        {"name": "Jojo Wollacott",      "position": "POR", "number": 12},
        {"name": "Richard Ofori",       "position": "POR", "number": 23},
        {"name": "Daniel Amartey",      "position": "DEF", "number": 5},
        {"name": "Alexander Djiku",     "position": "DEF", "number": 3},
        {"name": "Tariq Lamptey",       "position": "DEF", "number": 2},
        {"name": "Gideon Mensah",       "position": "DEF", "number": 3},
        {"name": "Thomas Partey",       "position": "MED", "number": 5},
        {"name": "Baba Rahman",         "position": "MED", "number": 3},
        {"name": "Salis Abdul Samed",   "position": "MED", "number": 8},
        {"name": "Mohammed Kudus",      "position": "MED", "number": 10},
        {"name": "Jordan Ayew",         "position": "DEL", "number": 7},
        {"name": "André Ayew",          "position": "DEL", "number": 10},
        {"name": "Inaki Williams",      "position": "DEL", "number": 9},
        {"name": "Antoine Semenyo",     "position": "DEL", "number": 11},
    ],
    "Panamá": [
        {"name": "Luis Mejía",          "position": "POR", "number": 1},
        {"name": "Jaime Penedo",        "position": "POR", "number": 23},
        {"name": "Orlando Mosquera",    "position": "POR", "number": 12},
        {"name": "Fidel Escobar",       "position": "DEF", "number": 5},
        {"name": "Harold Cummings",     "position": "DEF", "number": 4},
        {"name": "Éric Davis",          "position": "DEF", "number": 3},
        {"name": "Edgardo Fariña",      "position": "DEF", "number": 2},
        {"name": "Adalberto Carrasquilla","position": "MED", "number": 8},
        {"name": "Aníbal Godoy",        "position": "MED", "number": 6},
        {"name": "Alberto Quintero",    "position": "MED", "number": 11},
        {"name": "Rolando Blackburn",   "position": "MED", "number": 10},
        {"name": "Rolando Blackburn",   "position": "DEL", "number": 17},
        {"name": "Abdiel Arroyo",       "position": "DEL", "number": 9},
        {"name": "Gabriel Torres",      "position": "DEL", "number": 7},
        {"name": "Cecilio Waterman",    "position": "DEL", "number": 18},
    ],
}
