"""
world_cup_players_data.py
-------------------------
Plantillas oficiales Mundial 2026 — 48 selecciones.
Datos temporales. Al terminar el torneo se reemplaza por plantillas de Liga MX.
"""

WC_SQUADS = {
    # ── GRUPO A ──
    "México": [
        {"number": 1, "name": "Raúl Rangel", "position": "POR"},
        {"number": 12, "name": "Carlos Acevedo", "position": "POR"},
        {"number": 13, "name": "Guillermo Ochoa", "position": "POR"},
        {"number": 2, "name": "Jorge Sánchez", "position": "DEF"},
        {"number": 3, "name": "César Montes", "position": "DEF"},
        {"number": 4, "name": "Johan Vásquez", "position": "DEF"},
        {"number": 5, "name": "Israel Reyes", "position": "DEF"},
        {"number": 6, "name": "Jesús Gallardo", "position": "DEF"},
        {"number": 14, "name": "Mateo Chávez", "position": "DEF"},
        {"number": 7, "name": "Luis Chávez", "position": "MED"},
        {"number": 8, "name": "Orbelín Pineda", "position": "MED"},
        {"number": 10, "name": "Álvaro Fidalgo", "position": "MED"},
        {"number": 15, "name": "Edson Álvarez", "position": "MED"},
        {"number": 16, "name": "Luis Romo", "position": "MED"},
        {"number": 18, "name": "Brian Gutiérrez", "position": "MED"},
        {"number": 20, "name": "Obed Vargas", "position": "MED"},
        {"number": 21, "name": "Gilberto Mora", "position": "MED"},
        {"number": 24, "name": "Erik Lira", "position": "MED"},
        {"number": 9, "name": "Raúl Jiménez", "position": "DEL"},
        {"number": 11, "name": "Guillermo Martínez", "position": "DEL"},
        {"number": 17, "name": "Julián Quiñones", "position": "DEL"},
        {"number": 19, "name": "Roberto Alvarado", "position": "DEL"},
        {"number": 22, "name": "César Huerta", "position": "DEL"},
        {"number": 23, "name": "Santiago Giménez", "position": "DEL"},
        {"number": 25, "name": "Alexis Vega", "position": "DEL"},
        {"number": 26, "name": "Armando González", "position": "DEL"},
    ],
    "Sudáfrica": [
        {"number": 1, "name": "Ronwen Williams", "position": "POR"},
        {"number": 16, "name": "Ricardo Goss", "position": "POR"},
        {"number": 22, "name": "Sipho Chaine", "position": "POR"},
        {"number": 2, "name": "Khuliso Mudau", "position": "DEF"},
        {"number": 3, "name": "Bradley Cross", "position": "DEF"},
        {"number": 4, "name": "Olwethu Makhanya", "position": "DEF"},
        {"number": 5, "name": "Thabang Matuludi", "position": "DEF"},
        {"number": 6, "name": "Aubrey Modiba", "position": "DEF"},
        {"number": 14, "name": "Knosinathi Sibisi", "position": "DEF"},
        {"number": 15, "name": "Khulumani Ndamane", "position": "DEF"},
        {"number": 24, "name": "Ime Okon", "position": "DEF"},
        {"number": 25, "name": "Samukele Kabini", "position": "DEF"},
        {"number": 26, "name": "Mbekezeli Mbokazi", "position": "DEF"},
        {"number": 8, "name": "Teboho Mokoena", "position": "MED"},
        {"number": 12, "name": "Jayden Adams", "position": "MED"},
        {"number": 13, "name": "Sphephelo Sithole", "position": "MED"},
        {"number": 18, "name": "Thalente Mbatha", "position": "MED"},
        {"number": 7, "name": "Percy Tau", "position": "DEL"},
        {"number": 9, "name": "Evidence Makgopa", "position": "DEL"},
        {"number": 10, "name": "Themba Zwane", "position": "DEL"},
        {"number": 11, "name": "Lyle Foster", "position": "DEL"},
        {"number": 17, "name": "Thapelo Morena", "position": "DEL"},
        {"number": 19, "name": "Oswin Appollis", "position": "DEL"},
        {"number": 20, "name": "Iqraam Rayners", "position": "DEL"},
        {"number": 21, "name": "Relebohile Mokofoeng", "position": "DEL"},
        {"number": 23, "name": "Kamogelo Sebelebele", "position": "DEL"},
    ],
    "Corea del Sur": [
        {"number": 1, "name": "Kim Seung-gyu", "position": "POR"},
        {"number": 12, "name": "Jo Hyeon-woo", "position": "POR"},
        {"number": 21, "name": "Song Bum-keun", "position": "POR"},
        {"number": 4, "name": "Kim Min-jae", "position": "DEF"},
        {"number": 2, "name": "Kim Moon-hwan", "position": "DEF"},
        {"number": 3, "name": "Jo Yu-min", "position": "DEF"},
        {"number": 5, "name": "Lee Han-beom", "position": "DEF"},
        {"number": 15, "name": "Kim Tae-hyun", "position": "DEF"},
        {"number": 16, "name": "Park Jin-seop", "position": "DEF"},
        {"number": 19, "name": "Lee Ki-hyeok", "position": "DEF"},
        {"number": 22, "name": "Seol Young-woo", "position": "DEF"},
        {"number": 24, "name": "Lee Tae-seok", "position": "DEF"},
        {"number": 26, "name": "Jens Castrop", "position": "DEF"},
        {"number": 6, "name": "Hwang In-beom", "position": "MED"},
        {"number": 8, "name": "Paik Seung-ho", "position": "MED"},
        {"number": 10, "name": "Lee Jae-sung", "position": "MED"},
        {"number": 13, "name": "Lee Kang-in", "position": "MED"},
        {"number": 14, "name": "Jeong Woo-yeong", "position": "MED"},
        {"number": 17, "name": "Yang Hyun-jun", "position": "MED"},
        {"number": 18, "name": "Bae Jun-ho", "position": "MED"},
        {"number": 23, "name": "Um Ji-sung", "position": "MED"},
        {"number": 25, "name": "Lee Dong-gyeong", "position": "MED"},
        {"number": 7, "name": "Son Heung-min", "position": "DEL"},
        {"number": 9, "name": "Cho Gue-sung", "position": "DEL"},
        {"number": 11, "name": "Hwang Hee-chan", "position": "DEL"},
        {"number": 20, "name": "Oh Hyeon-gyu", "position": "DEL"},
    ],
    "Rep. Checa": [
        {"number": 1, "name": "Jindřich Staněk", "position": "POR"},
        {"number": 16, "name": "Matěj Kovář", "position": "POR"},
        {"number": 23, "name": "Lukáš Horníček", "position": "POR"},
        {"number": 3, "name": "Tomáš Holeš", "position": "DEF"},
        {"number": 4, "name": "Robin Hranáč", "position": "DEF"},
        {"number": 5, "name": "Vladimír Coufal", "position": "DEF"},
        {"number": 15, "name": "David Jurásek", "position": "DEF"},
        {"number": 18, "name": "Ladislav Krejčí", "position": "DEF"},
        {"number": 2, "name": "David Douděra", "position": "DEF"},
        {"number": 6, "name": "Štěpán Chaloupek", "position": "DEF"},
        {"number": 12, "name": "Jaroslav Zelený", "position": "DEF"},
        {"number": 24, "name": "David Zima", "position": "DEF"},
        {"number": 14, "name": "Lukáš Provod", "position": "MED"},
        {"number": 22, "name": "Tomáš Souček", "position": "MED"},
        {"number": 25, "name": "Pavel Šulc", "position": "MED"},
        {"number": 8, "name": "Lukáš Červ", "position": "MED"},
        {"number": 13, "name": "Vladimír Darida", "position": "MED"},
        {"number": 20, "name": "Hugo Sochůrek", "position": "MED"},
        {"number": 21, "name": "Alexandr Sojka", "position": "MED"},
        {"number": 26, "name": "Denis Višinský", "position": "MED"},
        {"number": 9, "name": "Adam Hložek", "position": "DEL"},
        {"number": 10, "name": "Patrik Schick", "position": "DEL"},
        {"number": 11, "name": "Jan Kuchta", "position": "DEL"},
        {"number": 17, "name": "Mojmír Chytil", "position": "DEL"},
        {"number": 19, "name": "Tomáš Chorý", "position": "DEL"},
    ],

    # ── GRUPO B ──
    "Canadá": [
        {"number": 1, "name": "Dayne St. Clair", "position": "POR"},
        {"number": 16, "name": "Maxime Crépeau", "position": "POR"},
        {"number": 18, "name": "Owen Goodman", "position": "POR"},
        {"number": 2, "name": "Alistair Johnston", "position": "DEF"},
        {"number": 4, "name": "Moïse Bombito", "position": "DEF"},
        {"number": 5, "name": "Derek Cornelius", "position": "DEF"},
        {"number": 19, "name": "Alphonso Davies", "position": "DEF"},
        {"number": 22, "name": "Richie Laryea", "position": "DEF"},
        {"number": 3, "name": "Luc de Fougerolles", "position": "DEF"},
        {"number": 6, "name": "Alfie Jones", "position": "DEF"},
        {"number": 13, "name": "Niko Sigur", "position": "DEF"},
        {"number": 15, "name": "Joel Waterman", "position": "DEF"},
        {"number": 7, "name": "Stephen Eustáquio", "position": "MED"},
        {"number": 8, "name": "Ismaël Koné", "position": "MED"},
        {"number": 11, "name": "Liam Millar", "position": "MED"},
        {"number": 17, "name": "Tajon Buchanan", "position": "MED"},
        {"number": 21, "name": "Jonathan Osorio", "position": "MED"},
        {"number": 20, "name": "Jacob Shaffelburg", "position": "MED"},
        {"number": 26, "name": "Ali Ahmed", "position": "MED"},
        {"number": 10, "name": "Mathieu Choinière", "position": "MED"},
        {"number": 14, "name": "Marcelo Flores", "position": "MED"},
        {"number": 24, "name": "Nathan Saliba", "position": "MED"},
        {"number": 9, "name": "Cyle Larin", "position": "DEL"},
        {"number": 23, "name": "Jonathan David", "position": "DEL"},
        {"number": 25, "name": "Promise David", "position": "DEL"},
        {"number": 27, "name": "Tani Oluwaseyi", "position": "DEL"},
    ],
    "Bosnia": [
        {"number": 1, "name": "Nikola Vasilj", "position": "POR"},
        {"number": 12, "name": "Martin Zlomislić", "position": "POR"},
        {"number": 22, "name": "Osman Hadžikić", "position": "POR"},
        {"number": 3, "name": "Dennis Hadžikadunić", "position": "DEF"},
        {"number": 5, "name": "Sead Kolašinac", "position": "DEF"},
        {"number": 19, "name": "Nikola Katić", "position": "DEF"},
        {"number": 2, "name": "Amar Dedić", "position": "DEF"},
        {"number": 4, "name": "Nihad Mujakić", "position": "DEF"},
        {"number": 6, "name": "Tarik Muharemović", "position": "DEF"},
        {"number": 15, "name": "Stjepan Radeljić", "position": "DEF"},
        {"number": 24, "name": "Nidal Čelik", "position": "DEF"},
        {"number": 8, "name": "Benjamin Tahirović", "position": "MED"},
        {"number": 13, "name": "Ivan Bašić", "position": "MED"},
        {"number": 7, "name": "Amir Hadžiahmetović", "position": "MED"},
        {"number": 10, "name": "Ivan Šunjić", "position": "MED"},
        {"number": 14, "name": "Dženis Burnić", "position": "MED"},
        {"number": 16, "name": "Ermin Mahmić", "position": "MED"},
        {"number": 17, "name": "Amar Memić", "position": "MED"},
        {"number": 18, "name": "Armin Gigović", "position": "MED"},
        {"number": 20, "name": "Kerim Alajbegović", "position": "MED"},
        {"number": 21, "name": "Esmir Bajraktarević", "position": "MED"},
        {"number": 9, "name": "Edin Džeko", "position": "DEL"},
        {"number": 11, "name": "Ermedin Demirović", "position": "DEL"},
        {"number": 23, "name": "Haris Tabaković", "position": "DEL"},
        {"number": 25, "name": "Jovo Lukić", "position": "DEL"},
        {"number": 26, "name": "Samed Baždar", "position": "DEL"},
    ],
    "Qatar": [
        {"number": 1, "name": "Salah Zakaria", "position": "POR"},
        {"number": 22, "name": "Meshaal Barsham", "position": "POR"},
        {"number": 32, "name": "Mahmoud Abunada", "position": "POR"},
        {"number": 2, "name": "Pedro Miguel", "position": "DEF"},
        {"number": 5, "name": "Tarek Salman", "position": "DEF"},
        {"number": 12, "name": "Lucas Mendes", "position": "DEF"},
        {"number": 15, "name": "Bassam Al-Rawi", "position": "DEF"},
        {"number": 16, "name": "Boualem Khoukhi", "position": "DEF"},
        {"number": 3, "name": "Sultan Al Brake", "position": "DEF"},
        {"number": 13, "name": "Ayoub Al-Alawi", "position": "DEF"},
        {"number": 14, "name": "Rayyan Al-Ali", "position": "DEF"},
        {"number": 24, "name": "Niall Mason", "position": "DEF"},
        {"number": 20, "name": "Ahmed Fathy", "position": "MED"},
        {"number": 26, "name": "Jassem Gaber", "position": "MED"},
        {"number": 8, "name": "Abdulaziz Hatem", "position": "MED"},
        {"number": 18, "name": "Assim Madibo", "position": "MED"},
        {"number": 25, "name": "Mohammed Mannai", "position": "MED"},
        {"number": 10, "name": "Hassan Al-Haydos", "position": "DEL"},
        {"number": 11, "name": "Akram Afif", "position": "DEL"},
        {"number": 19, "name": "Almoez Ali", "position": "DEL"},
        {"number": 7, "name": "Tahsin Mohammed", "position": "DEL"},
        {"number": 9, "name": "Edmílson Júnior", "position": "DEL"},
        {"number": 17, "name": "Ahmed Al-Ganehi", "position": "DEL"},
        {"number": 21, "name": "Ahmed Alaa", "position": "DEL"},
        {"number": 30, "name": "Mohammed Muntari", "position": "DEL"},
    ],
    "Suiza": [
        {"number": 21, "name": "Gregor Kobel", "position": "POR"},
        {"number": 1, "name": "Yvon Mvogo", "position": "POR"},
        {"number": 12, "name": "Marvin Keller", "position": "POR"},
        {"number": 4, "name": "Nico Elvedi", "position": "DEF"},
        {"number": 5, "name": "Manuel Akanji", "position": "DEF"},
        {"number": 13, "name": "Ricardo Rodríguez", "position": "DEF"},
        {"number": 3, "name": "Silvan Widmer", "position": "DEF"},
        {"number": 2, "name": "Miro Muheim", "position": "DEF"},
        {"number": 6, "name": "Aurèle Amenda", "position": "DEF"},
        {"number": 14, "name": "Eray Cömert", "position": "DEF"},
        {"number": 22, "name": "Luca Jaquez", "position": "DEF"},
        {"number": 8, "name": "Remo Freuler", "position": "MED"},
        {"number": 10, "name": "Granit Xhaka", "position": "MED"},
        {"number": 20, "name": "Michel Aebischer", "position": "MED"},
        {"number": 26, "name": "Fabian Rieder", "position": "MED"},
        {"number": 15, "name": "Johan Manzambi", "position": "MED"},
        {"number": 16, "name": "Ardon Jashari", "position": "MED"},
        {"number": 17, "name": "Djibril Sow", "position": "MED"},
        {"number": 18, "name": "Christian Fassnacht", "position": "MED"},
        {"number": 7, "name": "Breel Embolo", "position": "DEL"},
        {"number": 9, "name": "Noah Okafor", "position": "DEL"},
        {"number": 19, "name": "Dan Ndoye", "position": "DEL"},
        {"number": 11, "name": "Zeki Amdouni", "position": "DEL"},
        {"number": 23, "name": "Cédric Itten", "position": "DEL"},
        {"number": 25, "name": "Ruben Vargas", "position": "DEL"},
    ],

    # ── GRUPO C ──
    "Brasil": [
        {"number": 1, "name": "Alisson Becker", "position": "POR"},
        {"number": 23, "name": "Ederson Moraes", "position": "POR"},
        {"number": 12, "name": "Weverton", "position": "POR"},
        {"number": 14, "name": "Gabriel Magalhães", "position": "DEF"},
        {"number": 4, "name": "Marquinhos", "position": "DEF"},
        {"number": 2, "name": "Danilo", "position": "DEF"},
        {"number": 3, "name": "Bremer", "position": "DEF"},
        {"number": 6, "name": "Alex Sandro", "position": "DEF"},
        {"number": 13, "name": "Douglas Santos", "position": "DEF"},
        {"number": 15, "name": "Léo Pereira", "position": "DEF"},
        {"number": 24, "name": "Roger Ibañez", "position": "DEF"},
        {"number": 25, "name": "Wesley França", "position": "DEF"},
        {"number": 8, "name": "Bruno Guimarães", "position": "MED"},
        {"number": 10, "name": "Lucas Paquetá", "position": "MED"},
        {"number": 5, "name": "Casemiro", "position": "MED"},
        {"number": 16, "name": "Danilo Santos", "position": "MED"},
        {"number": 18, "name": "Fabinho", "position": "MED"},
        {"number": 7, "name": "Vinícius Júnior", "position": "DEL"},
        {"number": 11, "name": "Raphinha", "position": "DEL"},
        {"number": 9, "name": "Endrick", "position": "DEL"},
        {"number": 21, "name": "Gabriel Martinelli", "position": "DEL"},
        {"number": 17, "name": "Igor Thiago", "position": "DEL"},
        {"number": 19, "name": "Luiz Henrique", "position": "DEL"},
        {"number": 20, "name": "Matheus Cunha", "position": "DEL"},
        {"number": 22, "name": "Rayan Vitor", "position": "DEL"},
    ],
    "Marruecos": [
        {"number": 1, "name": "Yassine Bounou", "position": "POR"},
        {"number": 12, "name": "Munir Kajoui", "position": "POR"},
        {"number": 22, "name": "Ahmed Reda Tagnaouti", "position": "POR"},
        {"number": 2, "name": "Achraf Hakimi", "position": "DEF"},
        {"number": 3, "name": "Noussair Mazraoui", "position": "DEF"},
        {"number": 5, "name": "Nayef Aguerd", "position": "DEF"},
        {"number": 4, "name": "Anass Salah-Eddine", "position": "DEF"},
        {"number": 6, "name": "Youssef Belammari", "position": "DEF"},
        {"number": 13, "name": "Issa Diop", "position": "DEF"},
        {"number": 14, "name": "Chadi Riad", "position": "DEF"},
        {"number": 15, "name": "Zakaria El Ouahdi", "position": "DEF"},
        {"number": 24, "name": "Redouane Halhal", "position": "DEF"},
        {"number": 8, "name": "Sofyan Amrabat", "position": "MED"},
        {"number": 18, "name": "Ismael Saibari", "position": "MED"},
        {"number": 23, "name": "Bilal El Khannouss", "position": "MED"},
        {"number": 10, "name": "Neil El Aynaoui", "position": "MED"},
        {"number": 16, "name": "Samir El Mourabet", "position": "MED"},
        {"number": 20, "name": "Ayyoub Bouaddi", "position": "MED"},
        {"number": 9, "name": "Ayoub El Kaabi", "position": "DEL"},
        {"number": 11, "name": "Brahim Díaz", "position": "DEL"},
        {"number": 17, "name": "Abde Ezzalzouli", "position": "DEL"},
        {"number": 19, "name": "Gessime Yassine", "position": "DEL"},
        {"number": 21, "name": "Ayoube Amaimouni", "position": "DEL"},
        {"number": 25, "name": "Chemsdine Talbi", "position": "DEL"},
    ],
    "Haití": [
        {"number": 1, "name": "Johny Placide", "position": "POR"},
        {"number": 12, "name": "Alexandre Pierre", "position": "POR"},
        {"number": 23, "name": "Josué Duverger", "position": "POR"},
        {"number": 2, "name": "Carlens Arcus", "position": "DEF"},
        {"number": 4, "name": "Ricardo Adé", "position": "DEF"},
        {"number": 5, "name": "Jean-Kévin Duverne", "position": "DEF"},
        {"number": 3, "name": "Wilguens Paugain", "position": "DEF"},
        {"number": 6, "name": "Duke Lacroix", "position": "DEF"},
        {"number": 13, "name": "Martin Expérience", "position": "DEF"},
        {"number": 14, "name": "Hannes Delcroix", "position": "DEF"},
        {"number": 15, "name": "Keeto Thermoncy", "position": "DEF"},
        {"number": 17, "name": "Danley Jean Jacques", "position": "MED"},
        {"number": 8, "name": "Carl Fred Sainté", "position": "MED"},
        {"number": 10, "name": "Jean-Ricner Bellegarde", "position": "MED"},
        {"number": 16, "name": "Woodensky Pierre", "position": "MED"},
        {"number": 18, "name": "Dominique Simon", "position": "MED"},
        {"number": 7, "name": "Duckens Nazon", "position": "DEL"},
        {"number": 9, "name": "Frantzdy Pierrot", "position": "DEL"},
        {"number": 11, "name": "Don Deedson Lauture", "position": "DEL"},
        {"number": 19, "name": "Josué Casimir", "position": "DEL"},
        {"number": 20, "name": "Ruben Providence", "position": "DEL"},
        {"number": 21, "name": "Wilson Isidor", "position": "DEL"},
        {"number": 24, "name": "Yassin Fortuné", "position": "DEL"},
        {"number": 25, "name": "Lenny Joseph", "position": "DEL"},
    ],
    "Escocia": [
        {"number": 1, "name": "Angus Gunn", "position": "POR"},
        {"number": 12, "name": "Craig Gordon", "position": "POR"},
        {"number": 22, "name": "Liam Kelly", "position": "POR"},
        {"number": 2, "name": "Anthony Ralston", "position": "DEF"},
        {"number": 3, "name": "Andrew Robertson", "position": "DEF"},
        {"number": 5, "name": "Grant Hanley", "position": "DEF"},
        {"number": 6, "name": "Kieran Tierney", "position": "DEF"},
        {"number": 13, "name": "Jack Hendry", "position": "DEF"},
        {"number": 26, "name": "Scott McKenna", "position": "DEF"},
        {"number": 4, "name": "Aaron Hickey", "position": "DEF"},
        {"number": 15, "name": "Dom Hyam", "position": "DEF"},
        {"number": 16, "name": "Nathan Patterson", "position": "DEF"},
        {"number": 24, "name": "John Souttar", "position": "DEF"},
        {"number": 7, "name": "John McGinn", "position": "MED"},
        {"number": 14, "name": "Billy Gilmour", "position": "MED"},
        {"number": 11, "name": "Ryan Christie", "position": "MED"},
        {"number": 23, "name": "Kenny McLean", "position": "MED"},
        {"number": 8, "name": "Finlay Curtis", "position": "MED"},
        {"number": 17, "name": "Lewis Ferguson", "position": "MED"},
        {"number": 18, "name": "Ben Doak", "position": "MED"},
        {"number": 10, "name": "Ché Adams", "position": "DEL"},
        {"number": 9, "name": "Lawrence Shankland", "position": "DEL"},
        {"number": 19, "name": "Lyndon Dykes", "position": "DEL"},
        {"number": 20, "name": "George Hirst", "position": "DEL"},
        {"number": 21, "name": "Ross Stewart", "position": "DEL"},
    ],

    # ── GRUPO D ──
    "USA": [
        {"number": 1, "name": "Matt Turner", "position": "POR"},
        {"number": 12, "name": "Matt Freese", "position": "POR"},
        {"number": 22, "name": "Chris Brady", "position": "POR"},
        {"number": 2, "name": "Sergiño Dest", "position": "DEF"},
        {"number": 3, "name": "Chris Richards", "position": "DEF"},
        {"number": 5, "name": "Antonee Robinson", "position": "DEF"},
        {"number": 13, "name": "Tim Ream", "position": "DEF"},
        {"number": 4, "name": "Max Arfsten", "position": "DEF"},
        {"number": 6, "name": "Alex Freeman", "position": "DEF"},
        {"number": 14, "name": "Mark McKenzie", "position": "DEF"},
        {"number": 15, "name": "Miles Robinson", "position": "DEF"},
        {"number": 24, "name": "Auston Trusty", "position": "DEF"},
        {"number": 8, "name": "Weston McKennie", "position": "MED"},
        {"number": 7, "name": "Giovanni Reyna", "position": "MED"},
        {"number": 10, "name": "Christian Pulisic", "position": "MED"},
        {"number": 11, "name": "Brenden Aaronson", "position": "MED"},
        {"number": 17, "name": "Malik Tillman", "position": "MED"},
        {"number": 21, "name": "Timothy Weah", "position": "MED"},
        {"number": 18, "name": "Cristian Roldan", "position": "MED"},
        {"number": 20, "name": "Alejandro Zendejas", "position": "MED"},
        {"number": 9, "name": "Folarin Balogun", "position": "DEL"},
        {"number": 19, "name": "Ricardo Pepi", "position": "DEL"},
        {"number": 23, "name": "Haji Wright", "position": "DEL"},
    ],
    "Australia": [
        {"number": 1, "name": "Mathew Ryan", "position": "POR"},
        {"number": 12, "name": "Patrick Beach", "position": "POR"},
        {"number": 18, "name": "Paul Izzo", "position": "POR"},
        {"number": 16, "name": "Aziz Behich", "position": "DEF"},
        {"number": 5, "name": "Jordan Bos", "position": "DEF"},
        {"number": 19, "name": "Harry Souttar", "position": "DEF"},
        {"number": 21, "name": "Cameron Burgess", "position": "DEF"},
        {"number": 2, "name": "Alessandro Circati", "position": "DEF"},
        {"number": 3, "name": "Milos Degenek", "position": "DEF"},
        {"number": 4, "name": "Jason Geria", "position": "DEF"},
        {"number": 13, "name": "Lucas Herrington", "position": "DEF"},
        {"number": 15, "name": "Jacob Italiano", "position": "DEF"},
        {"number": 24, "name": "Kai Trewin", "position": "DEF"},
        {"number": 8, "name": "Connor Metcalfe", "position": "MED"},
        {"number": 22, "name": "Jackson Irvine", "position": "MED"},
        {"number": 6, "name": "Cameron Devlin", "position": "MED"},
        {"number": 14, "name": "Ajdin Hrustic", "position": "MED"},
        {"number": 17, "name": "Aiden O'Neill", "position": "MED"},
        {"number": 20, "name": "Paul Okon-Engstler", "position": "MED"},
        {"number": 7, "name": "Mathew Leckie", "position": "DEL"},
        {"number": 9, "name": "Awer Mabil", "position": "DEL"},
        {"number": 10, "name": "Mohamed Toure", "position": "DEL"},
        {"number": 11, "name": "Nishan Velupillay", "position": "DEL"},
        {"number": 23, "name": "Cristian Volpato", "position": "DEL"},
        {"number": 25, "name": "Tete Yengi", "position": "DEL"},
    ],
    "Paraguay": [
        {"number": 1, "name": "Carlos Coronel", "position": "POR"},
        {"number": 12, "name": "Roberto Fernández", "position": "POR"},
        {"number": 22, "name": "Orlando Gill", "position": "POR"},
        {"number": 15, "name": "Gustavo Gómez", "position": "DEF"},
        {"number": 4, "name": "Junior Alonso", "position": "DEF"},
        {"number": 5, "name": "Fabián Balbuena", "position": "DEF"},
        {"number": 3, "name": "Omar Alderete", "position": "DEF"},
        {"number": 2, "name": "Juan Cáceres", "position": "DEF"},
        {"number": 6, "name": "Blas Riveros", "position": "DEF"},
        {"number": 13, "name": "Alan Benítez", "position": "DEF"},
        {"number": 14, "name": "Agustín Sández", "position": "DEF"},
        {"number": 10, "name": "Miguel Almirón", "position": "MED"},
        {"number": 23, "name": "Mathias Villasanti", "position": "MED"},
        {"number": 17, "name": "Alejandro Romero Gamarra", "position": "MED"},
        {"number": 16, "name": "Andrés Cubas", "position": "MED"},
        {"number": 24, "name": "Ramón Sosa", "position": "MED"},
        {"number": 21, "name": "Diego Gómez", "position": "MED"},
        {"number": 7, "name": "Damián Bobadilla", "position": "MED"},
        {"number": 8, "name": "Braian Ojeda", "position": "MED"},
        {"number": 19, "name": "Julio Enciso", "position": "DEL"},
        {"number": 11, "name": "Ángel Romero", "position": "DEL"},
        {"number": 25, "name": "Antonio Sanabria", "position": "DEL"},
        {"number": 18, "name": "Alex Arce", "position": "DEL"},
        {"number": 9, "name": "Adam Bareiro", "position": "DEL"},
        {"number": 20, "name": "Óscar Romero", "position": "DEL"},
    ],
    "Turquía": [
        {"number": 1, "name": "Mert Günok", "position": "POR"},
        {"number": 12, "name": "Altay Bayındır", "position": "POR"},
        {"number": 22, "name": "Ersin Destanoğlu", "position": "POR"},
        {"number": 14, "name": "Abdülkerim Bardakcı", "position": "DEF"},
        {"number": 20, "name": "Ferdi Kadıoğlu", "position": "DEF"},
        {"number": 3, "name": "Merih Demiral", "position": "DEF"},
        {"number": 18, "name": "Mert Müldür", "position": "DEF"},
        {"number": 4, "name": "Samet Akaydin", "position": "DEF"},
        {"number": 2, "name": "Ahmetcan Kaplan", "position": "DEF"},
        {"number": 5, "name": "Çağlar Söyüncü", "position": "DEF"},
        {"number": 6, "name": "Eren Elmalı", "position": "DEF"},
        {"number": 27, "name": "Zeki Çelik", "position": "DEF"},
        {"number": 10, "name": "Hakan Çalhanoğlu", "position": "MED"},
        {"number": 16, "name": "İsmail Yüksek", "position": "MED"},
        {"number": 8, "name": "Arda Güler", "position": "MED"},
        {"number": 21, "name": "Barış Alper Yılmaz", "position": "MED"},
        {"number": 31, "name": "Can Uzun", "position": "MED"},
        {"number": 19, "name": "Kenan Yıldız", "position": "DEL"},
        {"number": 7, "name": "Kerem Aktürkoğlu", "position": "DEL"},
        {"number": 25, "name": "Yunus Akgün", "position": "DEL"},
        {"number": 9, "name": "Deniz Gül", "position": "DEL"},
        {"number": 11, "name": "İrfan Can Kahveci", "position": "DEL"},
        {"number": 17, "name": "Oğuz Aydın", "position": "DEL"},
    ],

    # ── GRUPO E ──
    "Alemania": [
        {"number": 1, "name": "Manuel Neuer", "position": "POR"},
        {"number": 12, "name": "Oliver Baumann", "position": "POR"},
        {"number": 22, "name": "Alexander Nübel", "position": "POR"},
        {"number": 2, "name": "Antonio Rüdiger", "position": "DEF"},
        {"number": 4, "name": "Jonathan Tah", "position": "DEF"},
        {"number": 15, "name": "Nico Schlotterbeck", "position": "DEF"},
        {"number": 3, "name": "David Raum", "position": "DEF"},
        {"number": 5, "name": "Waldemar Anton", "position": "DEF"},
        {"number": 6, "name": "Nathaniel Brown", "position": "DEF"},
        {"number": 24, "name": "Malick Thiaw", "position": "DEF"},
        {"number": 6, "name": "Joshua Kimmich", "position": "MED"},
        {"number": 8, "name": "Aleksandar Pavlović", "position": "MED"},
        {"number": 13, "name": "Felix Nmecha", "position": "MED"},
        {"number": 14, "name": "Angelo Stiller", "position": "MED"},
        {"number": 16, "name": "Nadiem Amiri", "position": "MED"},
        {"number": 18, "name": "Leon Goretzka", "position": "MED"},
        {"number": 20, "name": "Jamie Leweling", "position": "MED"},
        {"number": 7, "name": "Kai Havertz", "position": "DEL"},
        {"number": 10, "name": "Jamal Musiala", "position": "DEL"},
        {"number": 17, "name": "Florian Wirtz", "position": "DEL"},
        {"number": 19, "name": "Leroy Sané", "position": "DEL"},
        {"number": 26, "name": "Deniz Undav", "position": "DEL"},
        {"number": 9, "name": "Maximilian Beier", "position": "DEL"},
        {"number": 11, "name": "Lennart Karl", "position": "DEL"},
        {"number": 21, "name": "Nick Woltemade", "position": "DEL"},
    ],
    "Curaçao": [
        {"number": 1, "name": "Eloy Room", "position": "POR"},
        {"number": 12, "name": "Tyrick Bodak", "position": "POR"},
        {"number": 22, "name": "Trevor Doornbusch", "position": "POR"},
        {"number": 5, "name": "Sherel Floranus", "position": "DEF"},
        {"number": 3, "name": "Juriën Gaari", "position": "DEF"},
        {"number": 4, "name": "Roshon van Eijma", "position": "DEF"},
        {"number": 2, "name": "Riechedly Bazoer", "position": "DEF"},
        {"number": 6, "name": "Joshua Brenet", "position": "DEF"},
        {"number": 13, "name": "Deveron Fonville", "position": "DEF"},
        {"number": 14, "name": "Armando Obispo", "position": "DEF"},
        {"number": 15, "name": "Shurandy Sambo", "position": "DEF"},
        {"number": 8, "name": "Leandro Bacuna", "position": "MED"},
        {"number": 10, "name": "Juninho Bacuna", "position": "MED"},
        {"number": 16, "name": "Godfried Roemeratoe", "position": "MED"},
        {"number": 17, "name": "Livano Comenencia", "position": "MED"},
        {"number": 18, "name": "Ar'jany Martha", "position": "MED"},
        {"number": 20, "name": "Tyrese Noslin", "position": "MED"},
        {"number": 11, "name": "Gervane Kastaneer", "position": "DEL"},
        {"number": 24, "name": "Brandley Kuwas", "position": "DEL"},
        {"number": 21, "name": "Jürgen Locadia", "position": "DEL"},
        {"number": 7, "name": "Tahith Chong", "position": "DEL"},
        {"number": 9, "name": "Sontje Hansen", "position": "DEL"},
        {"number": 19, "name": "Jearl Margaritha", "position": "DEL"},
    ],
    "Costa de Marfil": [
        {"number": 1, "name": "Yahia Fofana", "position": "POR"},
        {"number": 16, "name": "Mohamed Koné", "position": "POR"},
        {"number": 22, "name": "Alban Lafont", "position": "POR"},
        {"number": 2, "name": "Ousmane Diomande", "position": "DEF"},
        {"number": 3, "name": "Ghislain Konan", "position": "DEF"},
        {"number": 5, "name": "Wilfried Singo", "position": "DEF"},
        {"number": 21, "name": "Evan Ndicka", "position": "DEF"},
        {"number": 4, "name": "Emmanuel Agbadou", "position": "DEF"},
        {"number": 6, "name": "Clément Akpa", "position": "DEF"},
        {"number": 12, "name": "Willy Boly", "position": "DEF"},
        {"number": 8, "name": "Franck Kessié", "position": "MED"},
        {"number": 18, "name": "Ibrahim Sangaré", "position": "MED"},
        {"number": 14, "name": "Parfait Guiagon", "position": "MED"},
        {"number": 15, "name": "Christ Inao Okoye", "position": "MED"},
        {"number": 20, "name": "Jean Michaël Seri", "position": "MED"},
        {"number": 17, "name": "Simon Adingra", "position": "DEL"},
        {"number": 19, "name": "Nicolas Pépé", "position": "DEL"},
        {"number": 7, "name": "Ange-Yoan Bonny", "position": "DEL"},
        {"number": 9, "name": "Amad Diallo", "position": "DEL"},
        {"number": 10, "name": "Oumar Diakité", "position": "DEL"},
        {"number": 11, "name": "Yan Diomande", "position": "DEL"},
        {"number": 13, "name": "Evann Guessand", "position": "DEL"},
        {"number": 23, "name": "Bazoumana Touré", "position": "DEL"},
        {"number": 24, "name": "Elye Wahi", "position": "DEL"},
    ],
    "Ecuador": [
        {"number": 1, "name": "Hernán Galíndez", "position": "POR"},
        {"number": 12, "name": "Moisés Ramírez", "position": "POR"},
        {"number": 22, "name": "Gonzalo Valle", "position": "POR"},
        {"number": 2, "name": "Félix Torres", "position": "DEF"},
        {"number": 3, "name": "Piero Hincapié", "position": "DEF"},
        {"number": 4, "name": "Joel Ordóñez", "position": "DEF"},
        {"number": 6, "name": "Willian Pacho", "position": "DEF"},
        {"number": 7, "name": "Pervis Estupiñán", "position": "DEF"},
        {"number": 17, "name": "Ángelo Preciado", "position": "DEF"},
        {"number": 24, "name": "Yaimar Medina", "position": "DEF"},
        {"number": 25, "name": "Jackson Porozo", "position": "DEF"},
        {"number": 5, "name": "Jordy Alcívar", "position": "MED"},
        {"number": 8, "name": "Pedro Vite", "position": "MED"},
        {"number": 10, "name": "Kendry Páez", "position": "MED"},
        {"number": 14, "name": "Alan Franco", "position": "MED"},
        {"number": 18, "name": "John Yeboah", "position": "MED"},
        {"number": 19, "name": "Moisés Caicedo", "position": "MED"},
        {"number": 21, "name": "Denil Castillo", "position": "MED"},
        {"number": 9, "name": "Gonzalo Plata", "position": "DEL"},
        {"number": 11, "name": "Kevin Rodríguez", "position": "DEL"},
        {"number": 13, "name": "Enner Valencia", "position": "DEL"},
        {"number": 15, "name": "Alan Minda", "position": "DEL"},
        {"number": 16, "name": "Jordy Caicedo", "position": "DEL"},
        {"number": 20, "name": "Nilson Angulo", "position": "DEL"},
        {"number": 23, "name": "Anthony Valencia", "position": "DEL"},
        {"number": 26, "name": "Jeremy Arévalo", "position": "DEL"},
    ],

    # ── GRUPO F ──
    "Países Bajos": [
        {"number": 1, "name": "Bart Verbruggen", "position": "POR"},
        {"number": 12, "name": "Mark Flekken", "position": "POR"},
        {"number": 22, "name": "Robin Roefs", "position": "POR"},
        {"number": 4, "name": "Virgil van Dijk", "position": "DEF"},
        {"number": 5, "name": "Nathan Aké", "position": "DEF"},
        {"number": 22, "name": "Denzel Dumfries", "position": "DEF"},
        {"number": 15, "name": "Micky van de Ven", "position": "DEF"},
        {"number": 2, "name": "Jorrel Hato", "position": "DEF"},
        {"number": 3, "name": "Jurriën Timber", "position": "DEF"},
        {"number": 6, "name": "Jan Paul van Hecke", "position": "DEF"},
        {"number": 20, "name": "Teun Koopmeiners", "position": "MED"},
        {"number": 14, "name": "Tijjani Reijnders", "position": "MED"},
        {"number": 8, "name": "Frenkie de Jong", "position": "MED"},
        {"number": 10, "name": "Marten de Roon", "position": "MED"},
        {"number": 16, "name": "Ryan Gravenberch", "position": "MED"},
        {"number": 17, "name": "Guus Til", "position": "MED"},
        {"number": 18, "name": "Quinten Timber", "position": "MED"},
        {"number": 21, "name": "Mats Wieffer", "position": "MED"},
        {"number": 11, "name": "Cody Gakpo", "position": "DEL"},
        {"number": 7, "name": "Xavi Simons", "position": "DEL"},
        {"number": 19, "name": "Wout Weghorst", "position": "DEL"},
        {"number": 9, "name": "Brian Brobbey", "position": "DEL"},
        {"number": 13, "name": "Justin Kluivert", "position": "DEL"},
        {"number": 23, "name": "Crysencio Summerville", "position": "DEL"},
    ],
    "Japón": [
        {"number": 1, "name": "Zion Suzuki", "position": "POR"},
        {"number": 12, "name": "Keisuke Osako", "position": "POR"},
        {"number": 22, "name": "Tomoki Hayakawa", "position": "POR"},
        {"number": 3, "name": "Shogo Taniguchi", "position": "DEF"},
        {"number": 4, "name": "Ko Itakura", "position": "DEF"},
        {"number": 19, "name": "Hiroki Ito", "position": "DEF"},
        {"number": 2, "name": "Yukinari Sugawara", "position": "DEF"},
        {"number": 5, "name": "Yūto Nagatomo", "position": "DEF"},
        {"number": 6, "name": "Tsuyoshi Watanabe", "position": "DEF"},
        {"number": 15, "name": "Takehiro Tomiyasu", "position": "DEF"},
        {"number": 23, "name": "Ayumu Seko", "position": "DEF"},
        {"number": 14, "name": "Junya Ito", "position": "MED"},
        {"number": 10, "name": "Ritsu Doan", "position": "MED"},
        {"number": 13, "name": "Keito Nakamura", "position": "MED"},
        {"number": 20, "name": "Takefusa Kubo", "position": "MED"},
        {"number": 7, "name": "Kaoru Mitoma", "position": "MED"},
        {"number": 8, "name": "Junnosuke Suzuki", "position": "MED"},
        {"number": 11, "name": "Daichi Kamada", "position": "MED"},
        {"number": 16, "name": "Ao Tanaka", "position": "MED"},
        {"number": 9, "name": "Ayase Ueda", "position": "DEL"},
        {"number": 24, "name": "Koki Ogawa", "position": "DEL"},
        {"number": 25, "name": "Daizen Maeda", "position": "DEL"},
        {"number": 21, "name": "Kento Shiogai", "position": "DEL"},
        {"number": 26, "name": "Keisuke Goto", "position": "DEL"},
    ],
    "Suecia": [
        {"number": 1, "name": "Viktor Johansson", "position": "POR"},
        {"number": 12, "name": "Kristoffer Nordfeldt", "position": "POR"},
        {"number": 22, "name": "J. Widell Zetterström", "position": "POR"},
        {"number": 3, "name": "Victor Lindelöf", "position": "DEF"},
        {"number": 4, "name": "Isak Hien", "position": "DEF"},
        {"number": 2, "name": "Hjalmar Ekdal", "position": "DEF"},
        {"number": 5, "name": "Gabriel Gudmundsson", "position": "DEF"},
        {"number": 6, "name": "Emil Holm", "position": "DEF"},
        {"number": 13, "name": "Gustaf Lagerbielke", "position": "DEF"},
        {"number": 14, "name": "Erik Smith", "position": "DEF"},
        {"number": 15, "name": "Carl Starfelt", "position": "DEF"},
        {"number": 23, "name": "Elliot Stroud", "position": "DEF"},
        {"number": 8, "name": "Mattias Svanberg", "position": "MED"},
        {"number": 10, "name": "Taha Ali", "position": "MED"},
        {"number": 16, "name": "Yasin Ayari", "position": "MED"},
        {"number": 17, "name": "Lucas Bergvall", "position": "MED"},
        {"number": 18, "name": "Jesper Karlström", "position": "MED"},
        {"number": 19, "name": "Ken Sema", "position": "MED"},
        {"number": 20, "name": "Besfort Zeneli", "position": "MED"},
        {"number": 9, "name": "Alexander Isak", "position": "DEL"},
        {"number": 11, "name": "Viktor Gyökeres", "position": "DEL"},
        {"number": 7, "name": "Anthony Elanga", "position": "DEL"},
        {"number": 21, "name": "Alexander Bernhardsson", "position": "DEL"},
        {"number": 25, "name": "Benjamin Nygren", "position": "DEL"},
    ],
    "Túnez": [
        {"number": 1, "name": "Aymen Dahmen", "position": "POR"},
        {"number": 12, "name": "Sabri Ben Hessen", "position": "POR"},
        {"number": 22, "name": "Abdelmouhib Chamakh", "position": "POR"},
        {"number": 3, "name": "Montassar Talbi", "position": "DEF"},
        {"number": 2, "name": "Ali Abdi", "position": "DEF"},
        {"number": 4, "name": "Dylan Bronn", "position": "DEF"},
        {"number": 5, "name": "Omar Rekik", "position": "DEF"},
        {"number": 6, "name": "Yan Valery", "position": "DEF"},
        {"number": 13, "name": "Moutaz Neffati", "position": "DEF"},
        {"number": 14, "name": "Raed Chikhaoui", "position": "DEF"},
        {"number": 15, "name": "Adam Arous", "position": "DEF"},
        {"number": 23, "name": "M. Amine Ben Hamida", "position": "DEF"},
        {"number": 10, "name": "Hannibal Mejbri", "position": "MED"},
        {"number": 8, "name": "Anis Ben Slimane", "position": "MED"},
        {"number": 16, "name": "Hadj Mahmoud", "position": "MED"},
        {"number": 17, "name": "Rani Khedira", "position": "MED"},
        {"number": 18, "name": "Mortadha Ben Ouanes", "position": "MED"},
        {"number": 7, "name": "Ismaël Gharbi", "position": "DEL"},
        {"number": 9, "name": "Elias Saad", "position": "DEL"},
        {"number": 11, "name": "Sebastian Tounekti", "position": "DEL"},
        {"number": 19, "name": "Firas Chaouat", "position": "DEL"},
        {"number": 20, "name": "Khalil Ayari", "position": "DEL"},
        {"number": 21, "name": "Hazem Mastouri", "position": "DEL"},
        {"number": 24, "name": "Rayan Elloumi", "position": "DEL"},
    ],

    # ── GRUPO G ──
    "Bélgica": [
        {"number": 1, "name": "Thibaut Courtois", "position": "POR"},
        {"number": 12, "name": "Senne Lammens", "position": "POR"},
        {"number": 22, "name": "Mike Penders", "position": "POR"},
        {"number": 21, "name": "Timothy Castagne", "position": "DEF"},
        {"number": 3, "name": "Arthur Theate", "position": "DEF"},
        {"number": 15, "name": "Thomas Meunier", "position": "DEF"},
        {"number": 2, "name": "Zeno Debast", "position": "DEF"},
        {"number": 4, "name": "Maxim De Cuyper", "position": "DEF"},
        {"number": 5, "name": "Koni De Winter", "position": "DEF"},
        {"number": 6, "name": "Brandon Mechele", "position": "DEF"},
        {"number": 13, "name": "Nathan Ngoy", "position": "DEF"},
        {"number": 7, "name": "Kevin De Bruyne", "position": "MED"},
        {"number": 24, "name": "Amadou Onana", "position": "MED"},
        {"number": 8, "name": "Youri Tielemans", "position": "MED"},
        {"number": 16, "name": "Nicolas Raskin", "position": "MED"},
        {"number": 18, "name": "Hans Vanaken", "position": "MED"},
        {"number": 10, "name": "Romelu Lukaku", "position": "DEL"},
        {"number": 9, "name": "Leandro Trossard", "position": "DEL"},
        {"number": 11, "name": "Jérémy Doku", "position": "DEL"},
        {"number": 14, "name": "Dodi Lukebakio", "position": "DEL"},
        {"number": 17, "name": "Charles De Ketelaere", "position": "DEL"},
        {"number": 19, "name": "Matias Fernandez-Pardo", "position": "DEL"},
        {"number": 20, "name": "Diego Moreira", "position": "DEL"},
        {"number": 23, "name": "Alexis Saelemaekers", "position": "DEL"},
    ],
    "Egipto": [
        {"number": 1, "name": "Mohamed El Shenawy", "position": "POR"},
        {"number": 16, "name": "Mostafa Shobeir", "position": "POR"},
        {"number": 22, "name": "El Mahdi Soliman", "position": "POR"},
        {"number": 3, "name": "Mohamed Abdelmonem", "position": "DEF"},
        {"number": 24, "name": "Rami Rabia", "position": "DEF"},
        {"number": 5, "name": "Hamdy Fathi", "position": "DEF"},
        {"number": 2, "name": "Mohamed Hany", "position": "DEF"},
        {"number": 4, "name": "Tarek Alaa", "position": "DEF"},
        {"number": 6, "name": "Yasser Ibrahim", "position": "DEF"},
        {"number": 12, "name": "Hossam Abdelmaguid", "position": "DEF"},
        {"number": 13, "name": "Ahmed Fatouh", "position": "DEF"},
        {"number": 14, "name": "Karim Hafez", "position": "DEF"},
        {"number": 8, "name": "Emam Ashour", "position": "MED"},
        {"number": 25, "name": "Ahmed Sayed Zizo", "position": "MED"},
        {"number": 7, "name": "Mahmoud Trezeguet", "position": "MED"},
        {"number": 15, "name": "Mohanad Lasheen", "position": "MED"},
        {"number": 17, "name": "Nabil Emad", "position": "MED"},
        {"number": 18, "name": "Mahmoud Saber", "position": "MED"},
        {"number": 20, "name": "Mostafa Ziko", "position": "MED"},
        {"number": 21, "name": "Ibrahim Adel", "position": "MED"},
        {"number": 10, "name": "Mohamed Salah", "position": "DEL"},
        {"number": 19, "name": "Omar Marmoush", "position": "DEL"},
        {"number": 9, "name": "Aqtay Abdallah", "position": "DEL"},
        {"number": 11, "name": "Hamza Abdelkarim", "position": "DEL"},
    ],
    "Irán": [
        {"number": 1, "name": "Alireza Beiranvand", "position": "POR"},
        {"number": 12, "name": "Payam Niazmand", "position": "POR"},
        {"number": 22, "name": "Hossein Hosseini", "position": "POR"},
        {"number": 2, "name": "Shojae Khalilzadeh", "position": "DEF"},
        {"number": 3, "name": "Ehsan Hajsafi", "position": "DEF"},
        {"number": 5, "name": "Milad Mohammadi", "position": "DEF"},
        {"number": 13, "name": "Hossein Kanaani", "position": "DEF"},
        {"number": 4, "name": "Danial Eiri", "position": "DEF"},
        {"number": 6, "name": "Saleh Hardani", "position": "DEF"},
        {"number": 14, "name": "Ali Nemati", "position": "DEF"},
        {"number": 15, "name": "Omid Noorafkan", "position": "DEF"},
        {"number": 21, "name": "Ramin Rezaeian", "position": "DEF"},
        {"number": 10, "name": "Saman Ghoddos", "position": "MED"},
        {"number": 14, "name": "Alireza Jahanbakhsh", "position": "MED"},
        {"number": 26, "name": "Mehdi Ghaedi", "position": "MED"},
        {"number": 7, "name": "Mohammad Ghorbani", "position": "MED"},
        {"number": 8, "name": "Mohammad Mohebi", "position": "MED"},
        {"number": 16, "name": "Mohammad Razzaghinia", "position": "MED"},
        {"number": 18, "name": "Mehdi Torabi", "position": "MED"},
        {"number": 23, "name": "Aria Yousefi", "position": "MED"},
        {"number": 9, "name": "Mehdi Taremi", "position": "DEL"},
        {"number": 20, "name": "Sardar Azmoun", "position": "DEL"},
        {"number": 11, "name": "Ali Alipour", "position": "DEL"},
        {"number": 17, "name": "Dennis Dargahi", "position": "DEL"},
        {"number": 19, "name": "Hadi Habibinejad", "position": "DEL"},
    ],
    "Nueva Zelanda": [
        {"number": 22, "name": "Max Crocombe", "position": "POR"},
        {"number": 12, "name": "Alex Paulsen", "position": "POR"},
        {"number": 1, "name": "Michael Woud", "position": "POR"},
        {"number": 2, "name": "Tim Payne", "position": "DEF"},
        {"number": 3, "name": "Liberato Cacace", "position": "DEF"},
        {"number": 5, "name": "Michael Boxall", "position": "DEF"},
        {"number": 4, "name": "Nando Pijnaker", "position": "DEF"},
        {"number": 13, "name": "Tommy Smith", "position": "DEF"},
        {"number": 6, "name": "Francis De Vries", "position": "DEF"},
        {"number": 14, "name": "Tyler Bindon", "position": "DEF"},
        {"number": 15, "name": "Finn Surman", "position": "DEF"},
        {"number": 16, "name": "Callan Elliot", "position": "DEF"},
        {"number": 18, "name": "Matthew Garbett", "position": "MED"},
        {"number": 8, "name": "Marko Stamenic", "position": "MED"},
        {"number": 10, "name": "Sarpreet Singh", "position": "MED"},
        {"number": 17, "name": "Alex Rufer", "position": "MED"},
        {"number": 20, "name": "Ryan Thomas", "position": "MED"},
        {"number": 9, "name": "Chris Wood", "position": "DEL"},
        {"number": 7, "name": "Eli Just", "position": "DEL"},
        {"number": 11, "name": "Ben Waine", "position": "DEL"},
        {"number": 19, "name": "Ben Old", "position": "DEL"},
        {"number": 23, "name": "Callum McCowatt", "position": "DEL"},
        {"number": 24, "name": "Jesse Randall", "position": "DEL"},
        {"number": 25, "name": "Lachlan Bayliss", "position": "DEL"},
    ],

    # ── GRUPO H ──
    "España": [
        {"number": 1, "name": "David Raya", "position": "POR"},
        {"number": 12, "name": "Unai Simón", "position": "POR"},
        {"number": 22, "name": "Joan García", "position": "POR"},
        {"number": 24, "name": "Marc Cucurella", "position": "DEF"},
        {"number": 14, "name": "Aymeric Laporte", "position": "DEF"},
        {"number": 2, "name": "Pau Cubarsí", "position": "DEF"},
        {"number": 3, "name": "Pedro Porro", "position": "DEF"},
        {"number": 4, "name": "Eric García", "position": "DEF"},
        {"number": 5, "name": "Marcos Llorente", "position": "DEF"},
        {"number": 6, "name": "Marc Pubill", "position": "DEF"},
        {"number": 16, "name": "Rodri", "position": "MED"},
        {"number": 20, "name": "Pedri", "position": "MED"},
        {"number": 18, "name": "Martin Zubimendi", "position": "MED"},
        {"number": 8, "name": "Fabián Ruiz", "position": "MED"},
        {"number": 10, "name": "Gavi", "position": "MED"},
        {"number": 15, "name": "Álex Baena", "position": "MED"},
        {"number": 19, "name": "Lamine Yamal", "position": "DEL"},
        {"number": 17, "name": "Nico Williams", "position": "DEL"},
        {"number": 11, "name": "Ferran Torres", "position": "DEL"},
        {"number": 21, "name": "Mikel Oyarzabal", "position": "DEL"},
        {"number": 7, "name": "Yéremy Pino", "position": "DEL"},
        {"number": 9, "name": "Borja Iglesias", "position": "DEL"},
        {"number": 23, "name": "Víctor Muñoz", "position": "DEL"},
    ],
    "Cabo Verde": [
        {"number": 1, "name": "Vozinha Dias", "position": "POR"},
        {"number": 12, "name": "Marcio Rosa", "position": "POR"},
        {"number": 22, "name": "CJ dos Santos", "position": "POR"},
        {"number": 2, "name": "Steven Moreira", "position": "DEF"},
        {"number": 3, "name": "Wagner Pina", "position": "DEF"},
        {"number": 4, "name": "João Paulo", "position": "DEF"},
        {"number": 5, "name": "Sidny Lopes", "position": "DEF"},
        {"number": 6, "name": "Logan Costa", "position": "DEF"},
        {"number": 13, "name": "Pico Lopes", "position": "DEF"},
        {"number": 14, "name": "Kelvin Pires", "position": "DEF"},
        {"number": 15, "name": "Stopira Brito", "position": "DEF"},
        {"number": 24, "name": "Diney Borges", "position": "DEF"},
        {"number": 8, "name": "Jamiro Monteiro", "position": "MED"},
        {"number": 10, "name": "Telmo Arcanjo", "position": "MED"},
        {"number": 16, "name": "Yannick Semedo", "position": "MED"},
        {"number": 17, "name": "Laros Duarte", "position": "MED"},
        {"number": 18, "name": "Deroy Duarte", "position": "MED"},
        {"number": 20, "name": "Kevin Pina", "position": "MED"},
        {"number": 7, "name": "Ryan Mendes", "position": "DEL"},
        {"number": 9, "name": "Willy Semedo", "position": "DEL"},
        {"number": 11, "name": "Garry Rodrigues", "position": "DEL"},
        {"number": 19, "name": "Jovane Cabral", "position": "DEL"},
        {"number": 21, "name": "Nuno da Costa", "position": "DEL"},
        {"number": 23, "name": "Dailon Livramento", "position": "DEL"},
        {"number": 25, "name": "Gilson Benchimol", "position": "DEL"},
        {"number": 26, "name": "Helio Varela", "position": "DEL"},
    ],
    "Arabia Saudita": [
        {"number": 1, "name": "Mohammed Al-Owais", "position": "POR"},
        {"number": 21, "name": "Ahmed Al-Kassar", "position": "POR"},
        {"number": 22, "name": "Raghed Al-Najjar", "position": "POR"},
        {"number": 2, "name": "Sultan Al-Ghannam", "position": "DEF"},
        {"number": 3, "name": "Aoun Al-Saluli", "position": "DEF"},
        {"number": 4, "name": "Ali Lajami", "position": "DEF"},
        {"number": 5, "name": "Ali Al-Bulayhi", "position": "DEF"},
        {"number": 12, "name": "Saud Abdulhamid", "position": "DEF"},
        {"number": 13, "name": "Yasser Al-Shahrani", "position": "DEF"},
        {"number": 15, "name": "Hassan Kadesh", "position": "DEF"},
        {"number": 23, "name": "Rayan Hamed", "position": "DEF"},
        {"number": 24, "name": "Mohammed Al-Breik", "position": "DEF"},
        {"number": 6, "name": "Nasser Al-Dawsari", "position": "MED"},
        {"number": 7, "name": "Mukhtar Ali", "position": "MED"},
        {"number": 8, "name": "Abdulelah Al-Malki", "position": "MED"},
        {"number": 14, "name": "Faisal Al-Ghamdi", "position": "MED"},
        {"number": 16, "name": "Sami Al-Najei", "position": "MED"},
        {"number": 18, "name": "Musab Al-Juwayr", "position": "MED"},
        {"number": 25, "name": "Abbas Al-Hassan", "position": "MED"},
        {"number": 26, "name": "Mohamed Kanno", "position": "MED"},
        {"number": 9, "name": "Firas Al-Buraikan", "position": "DEL"},
        {"number": 10, "name": "Salem Al-Dawsari", "position": "DEL"},
        {"number": 11, "name": "Saleh Al-Shehri", "position": "DEL"},
        {"number": 17, "name": "Abdullah Radif", "position": "DEL"},
        {"number": 19, "name": "Fahad Al-Muwallad", "position": "DEL"},
        {"number": 20, "name": "Abdulrahman Ghareeb", "position": "DEL"},
    ],
    "Uruguay": [
        {"number": 1, "name": "Sergio Rochet", "position": "POR"},
        {"number": 12, "name": "Fernando Muslera", "position": "POR"},
        {"number": 22, "name": "Santiago Mele", "position": "POR"},
        {"number": 4, "name": "Ronald Araújo", "position": "DEF"},
        {"number": 2, "name": "José María Giménez", "position": "DEF"},
        {"number": 16, "name": "Mathías Olivera", "position": "DEF"},
        {"number": 17, "name": "Matías Viña", "position": "DEF"},
        {"number": 3, "name": "Santiago Bueno", "position": "DEF"},
        {"number": 5, "name": "Sebastián Cáceres", "position": "DEF"},
        {"number": 6, "name": "Guillermo Varela", "position": "DEF"},
        {"number": 13, "name": "Joaquín Piquerez", "position": "DEF"},
        {"number": 15, "name": "Federico Valverde", "position": "MED"},
        {"number": 20, "name": "Rodrigo Bentancur", "position": "MED"},
        {"number": 10, "name": "Giorgian de Arrascaeta", "position": "MED"},
        {"number": 7, "name": "Nicolás de la Cruz", "position": "MED"},
        {"number": 11, "name": "Facundo Pellistri", "position": "MED"},
        {"number": 18, "name": "Brian Rodríguez", "position": "MED"},
        {"number": 8, "name": "Emiliano Martínez", "position": "MED"},
        {"number": 21, "name": "Rodrigo Zalazar", "position": "MED"},
        {"number": 23, "name": "Agustín Canobbio", "position": "MED"},
        {"number": 24, "name": "Maximiliano Araújo", "position": "MED"},
        {"number": 19, "name": "Darwin Núñez", "position": "DEL"},
        {"number": 9, "name": "Rodrigo Aguirre", "position": "DEL"},
    ],

    # ── GRUPO I ──
    "Francia": [
        {"number": 16, "name": "Mike Maignan", "position": "POR"},
        {"number": 1, "name": "Robin Risser", "position": "POR"},
        {"number": 23, "name": "Brice Samba", "position": "POR"},
        {"number": 22, "name": "Theo Hernández", "position": "DEF"},
        {"number": 5, "name": "Jules Koundé", "position": "DEF"},
        {"number": 17, "name": "William Saliba", "position": "DEF"},
        {"number": 4, "name": "Dayot Upamecano", "position": "DEF"},
        {"number": 15, "name": "Ibrahima Konaté", "position": "DEF"},
        {"number": 2, "name": "Lucas Digne", "position": "DEF"},
        {"number": 3, "name": "Malo Gusto", "position": "DEF"},
        {"number": 6, "name": "Lucas Hernández", "position": "DEF"},
        {"number": 12, "name": "Maxence Lacroix", "position": "DEF"},
        {"number": 8, "name": "Aurélien Tchouaméni", "position": "MED"},
        {"number": 14, "name": "Adrien Rabiot", "position": "MED"},
        {"number": 13, "name": "N'Golo Kanté", "position": "MED"},
        {"number": 18, "name": "Manu Koné", "position": "MED"},
        {"number": 20, "name": "Warren Zaïre-Emery", "position": "MED"},
        {"number": 10, "name": "Kylian Mbappé", "position": "DEL"},
        {"number": 15, "name": "Marcus Thuram", "position": "DEL"},
        {"number": 24, "name": "Bradley Barcola", "position": "DEL"},
        {"number": 7, "name": "Maghnes Akliouche", "position": "DEL"},
        {"number": 9, "name": "Rayan Cherki", "position": "DEL"},
        {"number": 11, "name": "Desiré Doué", "position": "DEL"},
        {"number": 19, "name": "Jean-Philippe Mateta", "position": "DEL"},
        {"number": 21, "name": "Michael Olise", "position": "DEL"},
    ],
    "Senegal": [
        {"number": 1, "name": "Alfred Gomis", "position": "POR"},
        {"number": 16, "name": "Édouard Mendy", "position": "POR"},
        {"number": 23, "name": "Mory Diaw", "position": "POR"},
        {"number": 2, "name": "Formose Mendy", "position": "DEF"},
        {"number": 3, "name": "Kalidou Koulibaly", "position": "DEF"},
        {"number": 4, "name": "Abdoulaye Seck", "position": "DEF"},
        {"number": 12, "name": "Fodé Ballo-Touré", "position": "DEF"},
        {"number": 13, "name": "Ismail Jakobs", "position": "DEF"},
        {"number": 14, "name": "Abdou Diallo", "position": "DEF"},
        {"number": 22, "name": "Abdoulaye Ndiaye", "position": "DEF"},
        {"number": 24, "name": "Mikayil Faye", "position": "DEF"},
        {"number": 5, "name": "Idrissa Gueye", "position": "MED"},
        {"number": 6, "name": "Nampalys Mendy", "position": "MED"},
        {"number": 8, "name": "Cheikhou Kouyaté", "position": "MED"},
        {"number": 15, "name": "Krépin Diatta", "position": "MED"},
        {"number": 17, "name": "Pape Sarr", "position": "MED"},
        {"number": 25, "name": "Lamine Camara", "position": "MED"},
        {"number": 26, "name": "Pape Gueye", "position": "MED"},
        {"number": 7, "name": "Nicolas Jackson", "position": "DEL"},
        {"number": 9, "name": "Bamba Dieng", "position": "DEL"},
        {"number": 10, "name": "Sadio Mané", "position": "DEL"},
        {"number": 11, "name": "Habib Diallo", "position": "DEL"},
        {"number": 18, "name": "Ismaïla Sarr", "position": "DEL"},
        {"number": 19, "name": "Iliman Ndiaye", "position": "DEL"},
        {"number": 20, "name": "Boulaye Dia", "position": "DEL"},
        {"number": 21, "name": "Amadou Sagna", "position": "DEL"},
    ],
    "Irak": [
        {"number": 1, "name": "Jalal Hassan", "position": "POR"},
        {"number": 12, "name": "Fahad Talib", "position": "POR"},
        {"number": 22, "name": "Ahmed Basil", "position": "POR"},
        {"number": 2, "name": "Hussein Ali", "position": "DEF"},
        {"number": 3, "name": "Manaf Younis", "position": "DEF"},
        {"number": 4, "name": "Saad Natiq", "position": "DEF"},
        {"number": 5, "name": "Rebin Sulaka", "position": "DEF"},
        {"number": 15, "name": "Merchas Doski", "position": "DEF"},
        {"number": 16, "name": "Zaid Tahseen", "position": "DEF"},
        {"number": 21, "name": "Ahmed Yahya", "position": "DEF"},
        {"number": 23, "name": "Frans Putros", "position": "DEF"},
        {"number": 24, "name": "Mustafa Saadoon", "position": "DEF"},
        {"number": 6, "name": "Amir Al-Ammari", "position": "MED"},
        {"number": 7, "name": "Zidane Iqbal", "position": "MED"},
        {"number": 8, "name": "Ibrahim Bayesh", "position": "MED"},
        {"number": 10, "name": "Youssef Amyn", "position": "MED"},
        {"number": 13, "name": "Bashar Resan", "position": "MED"},
        {"number": 14, "name": "Amjad Attwan", "position": "MED"},
        {"number": 18, "name": "Osama Rashid", "position": "MED"},
        {"number": 26, "name": "Kevin Yakob", "position": "MED"},
        {"number": 9, "name": "Aymen Hussein", "position": "DEL"},
        {"number": 11, "name": "Ali Al-Hamadi", "position": "DEL"},
        {"number": 17, "name": "Ali Jassim", "position": "DEL"},
        {"number": 19, "name": "Mohanand Ali", "position": "DEL"},
        {"number": 20, "name": "Ahmed Qasim", "position": "DEL"},
    ],
    "Noruega": [
        {"number": 1, "name": "Ørjan Nyland", "position": "POR"},
        {"number": 12, "name": "Egil Selvik", "position": "POR"},
        {"number": 23, "name": "Sander Tangvik", "position": "POR"},
        {"number": 2, "name": "Julian Ryerson", "position": "DEF"},
        {"number": 3, "name": "Kristoffer Ajer", "position": "DEF"},
        {"number": 4, "name": "Leo Østigård", "position": "DEF"},
        {"number": 5, "name": "David Wolfe", "position": "DEF"},
        {"number": 6, "name": "Marcus Pedersen", "position": "DEF"},
        {"number": 14, "name": "Fredrik Bjørkan", "position": "DEF"},
        {"number": 15, "name": "Torbjørn Heggem", "position": "DEF"},
        {"number": 16, "name": "Sondre Langås", "position": "DEF"},
        {"number": 21, "name": "Henrik Falchener", "position": "DEF"},
        {"number": 8, "name": "Martin Ødegaard", "position": "MED"},
        {"number": 10, "name": "Sander Berge", "position": "MED"},
        {"number": 11, "name": "Patrick Berg", "position": "MED"},
        {"number": 13, "name": "Fredrik Aursnes", "position": "MED"},
        {"number": 17, "name": "Kristian Thorstvedt", "position": "MED"},
        {"number": 18, "name": "Morten Thorsby", "position": "MED"},
        {"number": 20, "name": "Hugo Vetlesen", "position": "MED"},
        {"number": 22, "name": "Oscar Bobb", "position": "MED"},
        {"number": 24, "name": "Thelo Aasgaard", "position": "MED"},
        {"number": 7, "name": "Alexander Sørloth", "position": "DEL"},
        {"number": 9, "name": "Erling Haaland", "position": "DEL"},
        {"number": 19, "name": "Jørgen Larsen", "position": "DEL"},
        {"number": 25, "name": "Antonio Nusa", "position": "DEL"},
        {"number": 26, "name": "Jens Hauge", "position": "DEL"},
    ],

    # ── GRUPO J ──
    "Argentina": [
        {"number": 1, "name": "Emiliano Martínez", "position": "POR"},
        {"number": 12, "name": "Gerónimo Rulli", "position": "POR"},
        {"number": 23, "name": "Walter Benítez", "position": "POR"},
        {"number": 2, "name": "Cristian Romero", "position": "DEF"},
        {"number": 3, "name": "Nicolás Tagliafico", "position": "DEF"},
        {"number": 4, "name": "Gonzalo Montiel", "position": "DEF"},
        {"number": 6, "name": "Germán Pezzella", "position": "DEF"},
        {"number": 13, "name": "Nahuel Molina", "position": "DEF"},
        {"number": 19, "name": "Nicolás Otamendi", "position": "DEF"},
        {"number": 25, "name": "Lisandro Martínez", "position": "DEF"},
        {"number": 26, "name": "Leonardo Balerdi", "position": "DEF"},
        {"number": 5, "name": "Leandro Paredes", "position": "MED"},
        {"number": 7, "name": "Rodrigo De Paul", "position": "MED"},
        {"number": 8, "name": "Enzo Fernández", "position": "MED"},
        {"number": 14, "name": "Exequiel Palacios", "position": "MED"},
        {"number": 16, "name": "Giovani Lo Celso", "position": "MED"},
        {"number": 20, "name": "Alexis Mac Allister", "position": "MED"},
        {"number": 24, "name": "Valentin Carboni", "position": "MED"},
        {"number": 9, "name": "Julián Álvarez", "position": "DEL"},
        {"number": 10, "name": "Lionel Messi", "position": "DEL"},
        {"number": 11, "name": "Ángel Di María", "position": "DEL"},
        {"number": 15, "name": "Nicolás González", "position": "DEL"},
        {"number": 17, "name": "Alejandro Garnacho", "position": "DEL"},
        {"number": 18, "name": "Valentin Castellanos", "position": "DEL"},
        {"number": 21, "name": "Paulo Dybala", "position": "DEL"},
        {"number": 22, "name": "Lautaro Martínez", "position": "DEL"},
    ],
    "Argelia": [
        {"number": 1, "name": "Anthony Mandrea", "position": "POR"},
        {"number": 12, "name": "Oussama Benbot", "position": "POR"},
        {"number": 16, "name": "Mustapha Zeghba", "position": "POR"},
        {"number": 2, "name": "Aïssa Mandi", "position": "DEF"},
        {"number": 3, "name": "Rayan Aït-Nouri", "position": "DEF"},
        {"number": 5, "name": "Ahmed Touba", "position": "DEF"},
        {"number": 15, "name": "Jaouen Hadjam", "position": "DEF"},
        {"number": 20, "name": "Youcef Atal", "position": "DEF"},
        {"number": 21, "name": "Ramy Bensebaini", "position": "DEF"},
        {"number": 24, "name": "Kevin Van Den Kerkhof", "position": "DEF"},
        {"number": 6, "name": "Ramiz Zerrouki", "position": "MED"},
        {"number": 8, "name": "Houssem Aouar", "position": "MED"},
        {"number": 10, "name": "Sofiane Feghouli", "position": "MED"},
        {"number": 14, "name": "Hicham Boudaoui", "position": "MED"},
        {"number": 18, "name": "Ismaël Bennacer", "position": "MED"},
        {"number": 19, "name": "Nabil Bentaleb", "position": "MED"},
        {"number": 22, "name": "Farès Chaïbi", "position": "MED"},
        {"number": 7, "name": "Riyad Mahrez", "position": "DEL"},
        {"number": 9, "name": "Baghdad Bounedjah", "position": "DEL"},
        {"number": 11, "name": "Amine Gouiri", "position": "DEL"},
        {"number": 13, "name": "Islam Slimani", "position": "DEL"},
        {"number": 17, "name": "Saïd Benrahma", "position": "DEL"},
        {"number": 23, "name": "Mohamed Amoura", "position": "DEL"},
        {"number": 25, "name": "Anis Hadj Moussa", "position": "DEL"},
        {"number": 26, "name": "Monsef Bakrar", "position": "DEL"},
    ],
    "Austria": [
        {"number": 1, "name": "Heinz Lindner", "position": "POR"},
        {"number": 12, "name": "Patrick Pentz", "position": "POR"},
        {"number": 13, "name": "Niklas Hedl", "position": "POR"},
        {"number": 2, "name": "Maximilian Wöber", "position": "DEF"},
        {"number": 3, "name": "Stefan Posch", "position": "DEF"},
        {"number": 4, "name": "Kevin Danso", "position": "DEF"},
        {"number": 5, "name": "Philipp Lienhart", "position": "DEF"},
        {"number": 14, "name": "Leopold Querfeld", "position": "DEF"},
        {"number": 15, "name": "Philipp Mwene", "position": "DEF"},
        {"number": 16, "name": "Gernot Trauner", "position": "DEF"},
        {"number": 21, "name": "Flavius Daniliuc", "position": "DEF"},
        {"number": 6, "name": "Nicolas Seiwald", "position": "MED"},
        {"number": 8, "name": "Alexander Prass", "position": "MED"},
        {"number": 9, "name": "Marcel Sabitzer", "position": "MED"},
        {"number": 10, "name": "Florian Grillitsch", "position": "MED"},
        {"number": 17, "name": "Florian Kainz", "position": "MED"},
        {"number": 18, "name": "Romano Schmid", "position": "MED"},
        {"number": 19, "name": "Christoph Baumgartner", "position": "MED"},
        {"number": 20, "name": "Konrad Laimer", "position": "MED"},
        {"number": 22, "name": "Matthias Seidl", "position": "MED"},
        {"number": 7, "name": "Marko Arnautović", "position": "DEL"},
        {"number": 11, "name": "Michael Gregoritsch", "position": "DEL"},
        {"number": 23, "name": "Patrick Wimmer", "position": "DEL"},
        {"number": 24, "name": "Andreas Weimann", "position": "DEL"},
        {"number": 25, "name": "Maximilian Entrup", "position": "DEL"},
        {"number": 26, "name": "Marco Grüll", "position": "DEL"},
    ],
    "Jordania": [
        {"number": 1, "name": "Yazeed Abu Laila", "position": "POR"},
        {"number": 12, "name": "Noureddin Bani Amer", "position": "POR"},
        {"number": 22, "name": "Abdallah Al-Fakhouri", "position": "POR"},
        {"number": 2, "name": "Mohammad Abu Hashish", "position": "DEF"},
        {"number": 3, "name": "Abdallah Nasib", "position": "DEF"},
        {"number": 4, "name": "Bara Marie", "position": "DEF"},
        {"number": 5, "name": "Yazan Al-Arab", "position": "DEF"},
        {"number": 13, "name": "Feras Shelbaieh", "position": "DEF"},
        {"number": 14, "name": "Salem Al-Ajalin", "position": "DEF"},
        {"number": 15, "name": "Hijazi Maher", "position": "DEF"},
        {"number": 23, "name": "Ehsan Haddad", "position": "DEF"},
        {"number": 6, "name": "Noor Al-Rawabdeh", "position": "MED"},
        {"number": 8, "name": "Rajaei Ayed", "position": "MED"},
        {"number": 10, "name": "Musa Al-Taamari", "position": "MED"},
        {"number": 16, "name": "Saleh Rateb", "position": "MED"},
        {"number": 18, "name": "Ibrahim Sadeh", "position": "MED"},
        {"number": 19, "name": "Mahmoud Al-Mardi", "position": "MED"},
        {"number": 21, "name": "Nizar Al-Rashdan", "position": "MED"},
        {"number": 24, "name": "Youssef Abu Jbara", "position": "MED"},
        {"number": 7, "name": "Mohammad Abu Zreiq", "position": "DEL"},
        {"number": 9, "name": "Ali Olwan", "position": "DEL"},
        {"number": 11, "name": "Yazan Al-Naimat", "position": "DEL"},
        {"number": 17, "name": "Hamza Al-Dardour", "position": "DEL"},
        {"number": 20, "name": "Reziq Bani Hani", "position": "DEL"},
        {"number": 25, "name": "Anas Al-Awdat", "position": "DEL"},
        {"number": 26, "name": "Ibrahim Sabra", "position": "DEL"},
    ],

    # ── GRUPO K ──
    "Colombia": [
        {"number": 1, "name": "Camilo Vargas", "position": "POR"},
        {"number": 12, "name": "Álvaro Montero", "position": "POR"},
        {"number": 22, "name": "David Ospina", "position": "POR"},
        {"number": 2, "name": "Daniel Muñoz", "position": "DEF"},
        {"number": 3, "name": "Jhon Lucumí", "position": "DEF"},
        {"number": 4, "name": "Carlos Cuesta", "position": "DEF"},
        {"number": 5, "name": "Johan Mojica", "position": "DEF"},
        {"number": 6, "name": "Dávinson Sánchez", "position": "DEF"},
        {"number": 13, "name": "Santiago Arias", "position": "DEF"},
        {"number": 14, "name": "Yerry Mina", "position": "DEF"},
        {"number": 23, "name": "Cristian Borja", "position": "DEF"},
        {"number": 8, "name": "Jefferson Lerma", "position": "MED"},
        {"number": 10, "name": "James Rodríguez", "position": "MED"},
        {"number": 15, "name": "Jhon Arias", "position": "MED"},
        {"number": 16, "name": "Richard Ríos", "position": "MED"},
        {"number": 18, "name": "Kevin Castaño", "position": "MED"},
        {"number": 20, "name": "Juan Quintero", "position": "MED"},
        {"number": 21, "name": "Jorge Carrascal", "position": "MED"},
        {"number": 7, "name": "Luis Díaz", "position": "DEL"},
        {"number": 9, "name": "Jhon Córdoba", "position": "DEL"},
        {"number": 11, "name": "Jhon Durán", "position": "DEL"},
        {"number": 17, "name": "Rafael Borré", "position": "DEL"},
        {"number": 19, "name": "Yáser Asprilla", "position": "DEL"},
        {"number": 24, "name": "Luis Sinisterra", "position": "DEL"},
        {"number": 25, "name": "Juan Hernández", "position": "DEL"},
        {"number": 26, "name": "Mateo Cassierra", "position": "DEL"},
    ],
    "Portugal": [
        {"number": 1, "name": "Diogo Costa", "position": "POR"},
        {"number": 12, "name": "José Sá", "position": "POR"},
        {"number": 22, "name": "Rui Patrício", "position": "POR"},
        {"number": 2, "name": "Nélson Semedo", "position": "DEF"},
        {"number": 3, "name": "Pepe", "position": "DEF"},
        {"number": 4, "name": "Rúben Dias", "position": "DEF"},
        {"number": 5, "name": "Diogo Dalot", "position": "DEF"},
        {"number": 13, "name": "Danilo Pereira", "position": "DEF"},
        {"number": 14, "name": "Gonçalo Inácio", "position": "DEF"},
        {"number": 19, "name": "Nuno Mendes", "position": "DEF"},
        {"number": 20, "name": "João Cancelo", "position": "DEF"},
        {"number": 24, "name": "António Silva", "position": "DEF"},
        {"number": 6, "name": "João Palhinha", "position": "MED"},
        {"number": 8, "name": "Bruno Fernandes", "position": "MED"},
        {"number": 10, "name": "Bernardo Silva", "position": "MED"},
        {"number": 15, "name": "João Neves", "position": "MED"},
        {"number": 16, "name": "Matheus Nunes", "position": "MED"},
        {"number": 18, "name": "Rúben Neves", "position": "MED"},
        {"number": 23, "name": "Vitinha", "position": "MED"},
        {"number": 7, "name": "Cristiano Ronaldo", "position": "DEL"},
        {"number": 9, "name": "Gonçalo Ramos", "position": "DEL"},
        {"number": 11, "name": "João Félix", "position": "DEL"},
        {"number": 17, "name": "Rafael Leão", "position": "DEL"},
        {"number": 21, "name": "Diogo Jota", "position": "DEL"},
        {"number": 25, "name": "Pedro Neto", "position": "DEL"},
        {"number": 26, "name": "Francisco Conceição", "position": "DEL"},
    ],
    "DR Congo": [
        {"number": 1, "name": "Lionel Mpasi", "position": "POR"},
        {"number": 12, "name": "Dimitry Bertaud", "position": "POR"},
        {"number": 16, "name": "Timothy Fayulu", "position": "POR"},
        {"number": 2, "name": "Henoc Inonga", "position": "DEF"},
        {"number": 3, "name": "Arthur Masuaku", "position": "DEF"},
        {"number": 4, "name": "Chancel Mbemba", "position": "DEF"},
        {"number": 5, "name": "Dylan Batubinsika", "position": "DEF"},
        {"number": 13, "name": "Gédéon Kalulu", "position": "DEF"},
        {"number": 14, "name": "Joris Kayembe", "position": "DEF"},
        {"number": 21, "name": "Rocky Bushiri", "position": "DEF"},
        {"number": 24, "name": "Axel Tuanzebe", "position": "DEF"},
        {"number": 6, "name": "Aaron Tshibola", "position": "MED"},
        {"number": 8, "name": "Samuel Moutoussamy", "position": "MED"},
        {"number": 10, "name": "Théo Bongonda", "position": "MED"},
        {"number": 15, "name": "Charles Pickel", "position": "MED"},
        {"number": 18, "name": "Omenuke Mfulu", "position": "MED"},
        {"number": 22, "name": "Gael Kakuta", "position": "MED"},
        {"number": 25, "name": "Noah Sadiki", "position": "MED"},
        {"number": 7, "name": "Grady Diangana", "position": "DEL"},
        {"number": 9, "name": "Cédric Bakambu", "position": "DEL"},
        {"number": 11, "name": "Yoane Wissa", "position": "DEL"},
        {"number": 17, "name": "Elia Meschack", "position": "DEL"},
        {"number": 19, "name": "Fiston Mayele", "position": "DEL"},
        {"number": 23, "name": "Simon Banza", "position": "DEL"},
        {"number": 26, "name": "Silas Katompa", "position": "DEL"},
    ],
    "Uzbekistán": [
        {"number": 1, "name": "Utkir Yusupov", "position": "POR"},
        {"number": 12, "name": "Abduvohid Nematov", "position": "POR"},
        {"number": 21, "name": "Botirali Ergashev", "position": "POR"},
        {"number": 2, "name": "Abdukodir Khusanov", "position": "DEF"},
        {"number": 3, "name": "Khojiakbar Alijonov", "position": "DEF"},
        {"number": 4, "name": "Farrukh Sayfiev", "position": "DEF"},
        {"number": 5, "name": "Rustam Ashurmatov", "position": "DEF"},
        {"number": 13, "name": "Sherzod Nasrullaev", "position": "DEF"},
        {"number": 15, "name": "Umar Eshmurodov", "position": "DEF"},
        {"number": 23, "name": "Husniddin Aliqulov", "position": "DEF"},
        {"number": 25, "name": "Zafarmurod Abdurakhmatov", "position": "DEF"},
        {"number": 6, "name": "Azizbek Turgunboev", "position": "MED"},
        {"number": 7, "name": "Otabek Shukurov", "position": "MED"},
        {"number": 8, "name": "Jamshid Iskanderov", "position": "MED"},
        {"number": 9, "name": "Odiljon Hamrobekov", "position": "MED"},
        {"number": 10, "name": "Jaloliddin Masharipov", "position": "MED"},
        {"number": 14, "name": "Jamshid Boltaboev", "position": "MED"},
        {"number": 19, "name": "Abbosbek Fayzullaev", "position": "MED"},
        {"number": 22, "name": "Khozhimat Erkinov", "position": "MED"},
        {"number": 24, "name": "Diyor Kholmatov", "position": "MED"},
        {"number": 11, "name": "Oston Urunov", "position": "DEL"},
        {"number": 17, "name": "Igor Sergeev", "position": "DEL"},
        {"number": 18, "name": "Bobur Abdikholikov", "position": "DEL"},
        {"number": 20, "name": "Eldor Shomurodov", "position": "DEL"},
        {"number": 26, "name": "Azizbek Amonov", "position": "DEL"},
    ],

    # ── GRUPO L ──
    "Inglaterra": [
        {"number": 1, "name": "Jordan Pickford", "position": "POR"},
        {"number": 12, "name": "Dean Henderson", "position": "POR"},
        {"number": 22, "name": "James Trafford", "position": "POR"},
        {"number": 2, "name": "Reece James", "position": "DEF"},
        {"number": 3, "name": "Dan Burn", "position": "DEF"},
        {"number": 5, "name": "John Stones", "position": "DEF"},
        {"number": 6, "name": "Marc Guéhi", "position": "DEF"},
        {"number": 13, "name": "Ezri Konsa", "position": "DEF"},
        {"number": 14, "name": "Tino Livramento", "position": "DEF"},
        {"number": 15, "name": "Jarel Quansah", "position": "DEF"},
        {"number": 24, "name": "Djed Spence", "position": "DEF"},
        {"number": 4, "name": "Declan Rice", "position": "MED"},
        {"number": 8, "name": "Jude Bellingham", "position": "MED"},
        {"number": 10, "name": "Eberechi Eze", "position": "MED"},
        {"number": 16, "name": "Kobbie Mainoo", "position": "MED"},
        {"number": 18, "name": "Conor Gallagher", "position": "MED"},
        {"number": 19, "name": "Morgan Rogers", "position": "MED"},
        {"number": 20, "name": "Nico O'Reilly", "position": "MED"},
        {"number": 21, "name": "Elliot Anderson", "position": "MED"},
        {"number": 7, "name": "Bukayo Saka", "position": "DEL"},
        {"number": 9, "name": "Harry Kane", "position": "DEL"},
        {"number": 11, "name": "Marcus Rashford", "position": "DEL"},
        {"number": 17, "name": "Anthony Gordon", "position": "DEL"},
        {"number": 23, "name": "Ollie Watkins", "position": "DEL"},
        {"number": 25, "name": "Ivan Toney", "position": "DEL"},
        {"number": 26, "name": "Noni Madueke", "position": "DEL"},
    ],
    "Croacia": [
        {"number": 1, "name": "Dominik Livaković", "position": "POR"},
        {"number": 12, "name": "Nediljko Labrović", "position": "POR"},
        {"number": 23, "name": "Ivica Ivušić", "position": "POR"},
        {"number": 2, "name": "Josip Stanišić", "position": "DEF"},
        {"number": 3, "name": "Borna Sosa", "position": "DEF"},
        {"number": 4, "name": "Joško Gvardiol", "position": "DEF"},
        {"number": 5, "name": "Martin Erlić", "position": "DEF"},
        {"number": 6, "name": "Josip Šutalo", "position": "DEF"},
        {"number": 19, "name": "Borna Barišić", "position": "DEF"},
        {"number": 21, "name": "Domagoj Vida", "position": "DEF"},
        {"number": 22, "name": "Josip Juranović", "position": "DEF"},
        {"number": 7, "name": "Lovro Majer", "position": "MED"},
        {"number": 8, "name": "Mateo Kovačić", "position": "MED"},
        {"number": 10, "name": "Luka Modrić", "position": "MED"},
        {"number": 11, "name": "Marcelo Brozović", "position": "MED"},
        {"number": 15, "name": "Mario Pašalić", "position": "MED"},
        {"number": 18, "name": "Luka Ivanušec", "position": "MED"},
        {"number": 25, "name": "Luka Sučić", "position": "MED"},
        {"number": 26, "name": "Martin Baturina", "position": "MED"},
        {"number": 9, "name": "Andrej Kramarić", "position": "DEL"},
        {"number": 14, "name": "Ivan Perišić", "position": "DEL"},
        {"number": 16, "name": "Ante Budimir", "position": "DEL"},
        {"number": 17, "name": "Bruno Petković", "position": "DEL"},
        {"number": 20, "name": "Marko Pjaca", "position": "DEL"},
        {"number": 24, "name": "Marco Pašalić", "position": "DEL"},
    ],
    "Ghana": [
        {"number": 1, "name": "Lawrence Ati-Zigi", "position": "POR"},
        {"number": 12, "name": "Jojo Wollacott", "position": "POR"},
        {"number": 16, "name": "Frederick Asare", "position": "POR"},
        {"number": 2, "name": "Alidu Seidu", "position": "DEF"},
        {"number": 3, "name": "Tariq Lamptey", "position": "DEF"},
        {"number": 5, "name": "Mohammed Salisu", "position": "DEF"},
        {"number": 6, "name": "Alexander Djiku", "position": "DEF"},
        {"number": 14, "name": "Gideon Mensah", "position": "DEF"},
        {"number": 15, "name": "Joseph Aidoo", "position": "DEF"},
        {"number": 23, "name": "Denis Odoi", "position": "DEF"},
        {"number": 24, "name": "Abdul Mumin", "position": "DEF"},
        {"number": 4, "name": "Thomas Partey", "position": "MED"},
        {"number": 8, "name": "Majeed Ashimeru", "position": "MED"},
        {"number": 10, "name": "Andre Ayew", "position": "MED"},
        {"number": 20, "name": "Mohammed Kudus", "position": "MED"},
        {"number": 21, "name": "Salis Abdul Samed", "position": "MED"},
        {"number": 22, "name": "Elisha Owusu", "position": "MED"},
        {"number": 25, "name": "Baba Iddrisu", "position": "MED"},
        {"number": 7, "name": "Abdul Fatawu Issahaku", "position": "DEL"},
        {"number": 9, "name": "Jordan Ayew", "position": "DEL"},
        {"number": 11, "name": "Osman Bukari", "position": "DEL"},
        {"number": 13, "name": "Joseph Paintsil", "position": "DEL"},
        {"number": 17, "name": "Ernest Nuamah", "position": "DEL"},
        {"number": 18, "name": "Inaki Williams", "position": "DEL"},
        {"number": 19, "name": "Antoine Semenyo", "position": "DEL"},
        {"number": 26, "name": "Ibrahim Osman", "position": "DEL"},
    ],
    "Panamá": [
        {"number": 1, "name": "Orlando Mosquera", "position": "POR"},
        {"number": 12, "name": "César Samudio", "position": "POR"},
        {"number": 22, "name": "Luis Mejía", "position": "POR"},
        {"number": 2, "name": "César Blackman", "position": "DEF"},
        {"number": 3, "name": "José Córdoba", "position": "DEF"},
        {"number": 4, "name": "Eduardo Anderson", "position": "DEF"},
        {"number": 5, "name": "Érick Miller", "position": "DEF"},
        {"number": 14, "name": "Edgardo Fariña", "position": "DEF"},
        {"number": 15, "name": "Eric Davis", "position": "DEF"},
        {"number": 23, "name": "Michael Murillo", "position": "DEF"},
        {"number": 24, "name": "Fidel Escobar", "position": "DEF"},
        {"number": 6, "name": "Cristian Martínez", "position": "MED"},
        {"number": 7, "name": "José Luis Rodríguez", "position": "MED"},
        {"number": 8, "name": "Adalberto Carrasquilla", "position": "MED"},
        {"number": 10, "name": "Édgar Bárcenas", "position": "MED"},
        {"number": 16, "name": "Carlos Harvey", "position": "MED"},
        {"number": 20, "name": "Aníbal Godoy", "position": "MED"},
        {"number": 21, "name": "César Yanis", "position": "MED"},
        {"number": 25, "name": "Abdiel Ayarza", "position": "MED"},
        {"number": 26, "name": "Jovani Welch", "position": "MED"},
        {"number": 9, "name": "Eduardo Guerrero", "position": "DEL"},
        {"number": 11, "name": "Ismael Díaz", "position": "DEL"},
        {"number": 13, "name": "Freddy Góndola", "position": "DEL"},
        {"number": 17, "name": "José Fajardo", "position": "DEL"},
        {"number": 18, "name": "Cecilio Waterman", "position": "DEL"},
        {"number": 19, "name": "Kahiser Lenis", "position": "DEL"},
    ],
}
